### ISSUE TITLE
 Invalid pom: jaxb-xjc 2.1.16 has a wrong dependency to jaxb-core 2.1.16

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#1003]
The pom states a dependency to jaxb-core 2.1.6 which does not exist for the 2.1.x versions.

This bug for 2.1.16 was already reported in a comment of #984, and one stated to fix it, but the bug is closed now (without a fix).
So nobody is currently able to use 2.1.17, unless they use a fixed private pom.

Please fix all the versions stated in #984, too.
#### Affected Versions
[2.1.16]

**Comment by lukasj** [comment]
should have been fixed in 2.1.17
