### ISSUE TITLE
Misleading xjc Error Message

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#1008]
Using xjc against a schema file that specifies an invalid version for the xmlns jaxb version results in the following error message:
[ERROR] JAXB version attribute must be "1.0"

However, other versions are applicable such as 2.0 and 2.1

Example:

Schema with the following root element declarations:
xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
jaxb:version="2.2"
#### Affected Versions
[2.2.7]

**Comment by lukasj** [comment]
3.0 is the only one supported in the latest version, so fixed...
