### ISSUE TITLE
JAnnotationUse causes NPE in getAnnotationMembers()

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#1040]
If <tt>memberValues</tt> field is never added a parameter, then calling <tt>JAnnotationUse#getAnnotationMembers()</tt> causes NullPointerException. This is actual for annotations like `@XmlMixed`, which by definition don't have params.
#### Affected Versions
[2.2.7]

**Comment by lukasj** [comment]
fixed already
