### ISSUE TITLE
Wrong package test.t1 in txw2

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#1050]
Java files in txw2/src/test/java say they're in <tt>test.t1</tt> whereas they are in <tt>t1</tt>.

**Comment by highsource** [comment]
This seems to already have been fixed:

* https://github.com/eclipse-ee4j/jaxb-ri/blob/master/jaxb-ri/txw/runtime/src/test/java/t1/Foo.java
* https://github.com/eclipse-ee4j/jaxb-ri/blob/master/jaxb-ri/txw/runtime/src/test/java/t1/Main.java
* https://github.com/eclipse-ee4j/jaxb-ri/blob/master/jaxb-ri/txw/runtime/src/test/java/t1/package-info.java

all say `package t1;`
