### ISSUE TITLE
Code creating ClassLoader for ant tasks not working properly

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#1055]
The implementation in com.sun.tools.xjc.ClassLoaderBuilder#createProtectiveClassLoader#createProtectiveClassLoader() seems not to work properly. It should load always the latest API version (without need to use endorsed mechanism), but it probably worked well only for jdk6\.

```
// what does this really find for jdk >= jdk7 ?
            URL apiUrl = cl.getResource("javax/xml/bind/JAXBPermission.class"); 
            if(apiUrl==null)
throw new ClassNotFoundException("There's no JAXB 2.2 API in the classpath");

            cl = new URLClassLoader(new URL[]{ParallelWorldClassLoader.toJarUrl(apiUrl)},cl);
```

It has to be verified that it adds jaxb-api.jar, not rt.jar for jdk7+.
#### Affected Versions
[2.2.8 (JDK 8)]

**Comment by lukasj** [comment]
no longer an issue
