### ISSUE TITLE
XJC fails on RELAXNG_COMPACT compilation with datatype library "http://www.w3.org/2001/XMLSchema-datatypes" not recognized

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#1065]
When trying to compile the attached (or any) RNC file I get:

```
datatype library "http://www.w3.org/2001/XMLSchema-datatypes" not recognized
```

Possibly related to #128 and #465.

I believe a link to the datatype library is somehow broken.

**Comment by lukasj** [comment]
note that - as of 4.0.3 - xsdlib and relaxngDatatype libraries have to be obtained separately, ie from https://github.com/xmlark/msv and https://github.com/java-schema-utilities/relaxng-datatype-java; sample and known to work setup for maven projects can be seen [here](https://github.com/eclipse-ee4j/jaxb-ri/blob/a735b8169dbcf584c2ea65dd19f3c039a9616b2f/jaxb-ri/runtime/impl/pom.xml#L116-L127)

**Comment by veriktig** [comment]
With commit b7d1ff7a13cec 4.0.5 ri release I see:

java -cp jaxb-ri/jaxb-ri/xjc/target/xjctask-cp/*:jaxb-ri/jaxb-ri/xjc/target/* com.sun.tools.xjc.Driver -relaxng -extension jaxb-ri/jaxb-ri/samples/src/main/samples/relaxng/formula.rng
parsing a schema...
[ERROR] datatype library "http://www.w3.org/2001/XMLSchema-datatypes" not recognized
  line 68 of file:/home/fred/scandium/external/jaxb-ri/jaxb-ri/samples/src/main/samples/relaxng/formula.rng
