### ISSUE TITLE
Remove mentions of RELAXNG from the documentation and the CLI help until it somehow works

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#1068]
The <tt>xjc /?</tt> output prints the following out:

```
-relaxng           :  treat input as RELAX NG (experimental,unsupported)
  -relaxng-compact   :  treat input as RELAX NG compact syntax (experimental,unsupported)
```

This is formulated similar to:

```
-dtd               :  treat input as XML DTD (experimental,unsupported)
  -wsdl              :  treat input as WSDL and compile schemas inside it (experimental,unsupported)
```

As DTD and WSDL compilation do (more or less) work, I assumed, RELAXNG can be also works somehow.

This assumption costed be today 0.5 PT. I have tried to compile a minimal RELAXNG_COMPACT example and consequently encountered #1065, #1066 (which I worked around), and, finally #1067.

With these issue I can with confidence say that <tt>RELAXNG_COMPACT</tt> compilation simply does not work. This is different from just "unsupported" (which I would interpret as "we don't officially support this") or "experimental" (which I would interpret as "we haven't thoroughly tested it yet"). It just does not work, completely and probably for a long time already.

Therefore I would consider these command line options and the documentation to be misleading:

```
-relaxng           :  treat input as RELAX NG (experimental,unsupported)
  -relaxng-compact   :  treat input as RELAX NG compact syntax (experimental,unsupported)
```

It costed me today a few hundred euros worth of time invested.

Please remove the command line options and correct the documentation in order not to mislead further users.

Thank you.
#### Affected Versions
[2.2.11]

**Comment by lukasj** [comment]
should be removed by #1691
