### ISSUE TITLE
xjc mark-generated sometimes produces a wrong date value

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#1105]
When using the parameter "-mark-generated" to generate the @Generated annotation, the content of the date attribute may be wrong.

In fact, the PM dates are wrong as they stay at the AM format.

It's because the date pattern used for generating the ISO-8601 string is wrong.
It's "yyyy-MM-dd'T'hh:mm:ssZ" but it should be "yyyy-MM-dd'T'HH:mm:ssZ"

The code to fix is in **com.sun.tools.xjc.addon.at_generated.PluginImpl**

```
private String getISO8601Date() {
        if(date==null) {
            StringBuffer tstamp = new StringBuffer();
            tstamp.append((new SimpleDateFormat("yyyy-MM-dd'T'hh:mm:ssZ")).format(new Date()));
            // hack to get ISO 8601 style timezone - is there a better way that doesn't require
            // a bunch of timezone offset calculations?
            tstamp.insert(tstamp.length()-2, ':');
            date = tstamp.toString();
        }
        return date;
    }
```

Maven artifact : **com.sun.xml.bind:jaxb-xjc:2.2.11**

Thanks.
#### Environment
JDK 8, JDK 7
#### Affected Versions
[2.2.11]

**Comment by volkert-fastned** [comment]
Any news on this? I just encountered this issue.

**Comment by lukasj** [comment]
2.3.4/3.0.1 having the fix are out already
