### ISSUE TITLE
JAXB API change list umbrella

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#1122]
Bugfixes:
[https://bugs.openjdk.java.net/browse/JDK-8072839](https://bugs.openjdk.java.net/browse/JDK-8072839)
[https://bugs.openjdk.java.net/browse/JDK-8157311](https://bugs.openjdk.java.net/browse/JDK-8157311)
[https://bugs.openjdk.java.net/browse/JDK-8150173](https://bugs.openjdk.java.net/browse/JDK-8150173)
[https://bugs.openjdk.java.net/browse/JDK-8175552](https://bugs.openjdk.java.net/browse/JDK-8175552)

Javadoc issues:
[https://bugs.openjdk.java.net/browse/JDK-8077332](https://bugs.openjdk.java.net/browse/JDK-8077332)
[https://bugs.openjdk.java.net/browse/JDK-8133651](https://bugs.openjdk.java.net/browse/JDK-8133651)
[https://bugs.openjdk.java.net/browse/JDK-8145545](https://bugs.openjdk.java.net/browse/JDK-8145545)
[https://bugs.openjdk.java.net/browse/JDK-8163266](https://bugs.openjdk.java.net/browse/JDK-8163266)
[https://bugs.openjdk.java.net/browse/JDK-8146061](https://bugs.openjdk.java.net/browse/JDK-8146061)
#### Affected Versions
[2.3.0]

**Comment by lukasj** [comment]
all of these were addressed for SE 9, so likely fixed already
