### ISSUE TITLE
link to binary releases

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#1131]
Its not obvious where users should go to get binary releases.

Maven?  

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.sun.xml.bind%22%20AND%20a%3A%22jaxb-ri%22

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22javax.xml.bind%22%20AND%20a%3A%22jaxb-api%22

**Comment by lukasj** [comment]
https://github.com/eclipse-ee4j/jaxb-ri/releases do have pointer to binary zip as does the home page at https://eclipse-ee4j.github.io/jaxb-ri/ (which deserves an update :-/). https://search.maven.org/search?q=g:com.sun.xml.bind%20AND%20a:jaxb-ri can be used like an archive
