### ISSUE TITLE
XJC: anyAttribute ignored when combined with inheritance

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#1146]
Hi,

When using XJC 2.3.0 on the following schema, the anyAttribute is not processed, so the otherAttributes field in not generated in my bean:

```
<xsd:complexType name="jsonObject">
        <xsd:complexContent>
            <xsd:extension base="tns:jsonNode">
                <xsd:sequence>
                    <xsd:element ref="tns:jsonNode" minOccurs="0" maxOccurs="unbounded"/>
                </xsd:sequence>
                <xsd:attribute name="name" type="xsd:string" use="optional"/>
                <xsd:anyAttribute namespace="##any" processContents="lax"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>
```

When removing the inheritance, the otherAttributes field is properly generated:
@XmlAnyAttribute
private Map<QName, String> otherAttributes = new HashMap<QName, String>();

**Workaround**: use the last version supporting this combination, 2.1.10.

**Comment by lukasj** [comment]
fixed
