### ISSUE TITLE
Split package between jaxb-impl and jaxb-core prevents usage as JPMS module

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#1168]
Hi, as Java 11 doesn't come with the `java.xml.bind` module any longer, I tried to add the JAXB RI as JPMS modules to my application. This failed though due to split packages between the following two artifacts:

```xml
<dependency>
    <groupId>com.sun.xml.bind</groupId>
    <artifactId>jaxb-impl</artifactId>
    <version>2.3.0</version>
</dependency>
<dependency>
    <groupId>com.sun.xml.bind</groupId>
    <artifactId>jaxb-core</artifactId>
    <version>2.3.0</version>
</dependency>
```

If these are not the correct artifacts to use, which ones should I be using instead? Dmitry [was hinting](https://twitter.com/m0mus/status/968949479956209664) on Twitter that the split package issue supposedly is resolved, so I might just be using wrong artifacts. Note I also tried 

```xml
<dependency>
   <groupId>org.glassfish.jaxb</groupId>
   <artifactId>jaxb-runtime</artifactId>
   <version>2.3.0</version>
</dependency>
```

But this in turn pulled in core which again resulted in split package issues. Unfortunately, the user guide at https://javaee.github.io/jaxb-v2/doc/user-guide/ch03.html#deployment also doesn't provide instructions on how to use the JAXB RI as JPMS modules.

@bravehorsie, Dmitry was mentioning that you migt have the answer. Thanks for any help :)

**Comment by bravehorsie** [comment]
Fiexed in 2.3.1
