### ISSUE TITLE
jaxb-api 2.3.0 declares java.activation transitive dependency in module-info, but not in pom.xml

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#1207]
The jaxb-api 2.3.0 library has a dependency on the `java.activation` module, which has been removed from JDK 11. The dependency is declared in `module-info.java` but not in pom.xml:
http://search.maven.org/#artifactdetails%7Cjavax.xml.bind%7Cjaxb-api%7C2.3.0%7Cjar

It should be declared there as well, so clients of the jaxb-api don't have to discover this dependency at runtime due to `NoClassDefFoundError`

**Comment by bravehorsie** [comment]
Fixed in 2.3.1
