### ISSUE TITLE
xjc is unusable with JAVA 10

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#1208]
When JAVA 10 is used, JAXB-RI 2.3.0 xjc fails with the famous class not found exception.
In the pre-release of 2.4.0 it fails even more miserably, because the xjc.bat refers to the wrong folder (lib instead of mod) and the class path is incomplete.

The only way to use xjc under JAVA 10 is to use the executable xjc tool in the JAVA 10 distribution. I have yet to find the JAVA source code for that!

A "reference implementation" should really contain a version of xjc which can be executed.

**Comment by bravehorsie** [comment]
fixed in 2.3.1
