### ISSUE TITLE
Release 2.3.1-b180717.0505 is not visible in Maven Central/Repo

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#1213]
Hello,

there was a fix for the problem

"Fix XJC ant task to work without fork. "

created with this commit:

https://github.com/javaee/jaxb-v2/commit/dad8495f19078cb05302132f83dafda5b3dfa98b#diff-9e91db6a172b85bd4a5588d9aa151e85

We checked the released versions of jaxb and this bugfix can be found starting from the 
release 2.3.1-b180717.0505, but this release has never made it to Maven Central or Maven Repo.

We tried to get 2.4.x running, but we get a lot of dependency issues and compaitiblity problems there, therefore the most simple solution would be, if someone could create another 2.3.x release and make it official in Maven Central or make the release 2.3.1-b180717.0505 available there.

Thank you very much for the support in advance.
best Regards,

Reza

**Comment by jbliznak** [comment]
How is it going with publishing 2.3.1 to maven central?

**Comment by bravehorsie** [comment]
2.4.0-b180830.0438 which is released to central is very similar to what
2.3.1 in staging now contains. You can test with that until 2.3.1 release.

Roman

**Comment by lukasj** [comment]
It's on the way, should be there in <6hours

**Comment by bravehorsie** [comment]
2.3.1 is in central now, closing this issue.
