### ISSUE TITLE
Maven Coordinates for API and RI

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#1216]
Can you please publish the Maven Coordinates to be used for the following distinct cases?
* Maven Dependency on JAXB API (for _compilation_)
* Maven Dependency on JAXB RI (for _execution_)

Can you please disclose which version number _range_ to use to get the JAXB release contained in:
* JRE 9
* JRE 10

**Comment by mkarg** [comment]
@mkarg I am the original reporter.

**Comment by bravehorsie** [comment]
```xml
                <!-- API -->
                <dependency>
                    <groupId>javax.xml.bind</groupId>
                    <artifactId>jaxb-api</artifactId>
                    <version>${jaxb.version}</version>
                </dependency>

                <!-- Runtime -->
                <dependency>
                    <groupId>org.glassfish.jaxb</groupId>
                    <artifactId>jaxb-runtime</artifactId>
                    <version>${jaxb.version}</version>
                </dependency>
```
Please see [JAXB user guide ](https://javaee.github.io/jaxb-v2/doc/user-guide/ch03.html#deployment-maven-coordinates)for more details.
