### ISSUE TITLE
Why have you imported a copy of the source with no git history?

### ISSUE THREAD

**Issue by Stexxen** [eclipse-ee4j/jaxb-ri#1217]
and all the version branches are missing? 

In the progress report is says you are at 80%? 
I'm assuming I'm missing something?

**Comment by lukasj** [comment]
> Note that the Eclipse IP Team cannot validate the history of the initial contribution; the initial contribution must be provided in the form of a snapshot of the project code and must be committed as it is reviewed (i.e. old history must, unfortunately, be left behind).

from https://wiki.eclipse.org/Development_Resources/Contribution_Questionnaire#Initial_Contribution

**Comment by Stexxen** [comment]
But what about all the branches for the currently available version 2.3.0, 2.3.1 and 2.4

What if a bug fix needs to be back ported?

**Comment by lukasj** [comment]
versions <=2.3.1 are from https://github.com/javaee/jaxb-v2 repo, everything newer should come from this repo

**Comment by Stexxen** [comment]
yep, that would make sense, but that repo says it is archived and is now closed for issues?

**Comment by lukasj** [comment]
all issues were moved to this repo and new ones are supposed to be filed here
