### ISSUE TITLE
NoClassDefFoundError: javax/activation/DataSource on JDK11

### ISSUE THREAD

**Issue by jesperdj** [eclipse-ee4j/jaxb-ri#1222]
When you try to run a Java program that uses JAXB on JDK11, with the following two artifacts that are [mentioned](https://javaee.github.io/jaxb-v2/doc/user-guide/ch03.html#deployment-maven-coordinates) in the Users Guide, you will get a `NoClassDefFoundError` when you run the program:

- `javax.xml.bind:jaxb-api:2.3.0`
- `org.glassfish.jaxb:jaxb-runtime:2.3.0.1` (runtime scope)

Why: The JAXB RI requires the JavaBeans Activation Framework which is not present in JDK11 anymore. Adding the following dependency solves the problem:

- `javax.activation:javax.activation-api:1.2.0` (runtime scope)

Please mention this in the Users Guide, or make sure that its included as a transitive dependency.

**Comment by lukasj** [comment]
I believe this is solved in 2.3.1, can you check it, please?

**Comment by mchowdhury319** [comment]
I am using JDK 17 and gradle 7.4.2. I tried using:

    implementation('javax.xml.bind:jaxb-api:2.3.1')
    implementation('com.sun.xml.bind:jaxb-core:2.3.0')
    implementation('org.glassfish.jaxb:jaxb-runtime:2.3.1')
    implementation("jakarta.xml.bind:jakarta.xml.bind-api:2.3.2")
    implementation('com.sun.xml.bind:jaxb-impl:2.3.0')
    implementation('com.sun.activation:javax.activation:1.2.0')
but the issue is not resolved.

Any idea?

**Comment by lukasj** [comment]
`implementation('com.sun.xml.bind:jaxb-core:2.3.0')` vs `implementation('org.glassfish.jaxb:jaxb-runtime:2.3.1')` seems to be the problem here. Why 2 different versions of same library are used? Choose one and stick with it. The latest one is 2.3.7
