### ISSUE TITLE
SchemaGen broken for JDK 9+

### ISSUE THREAD

**Issue by lennartj** [eclipse-ee4j/jaxb-ri#1223]
Hello all,

When generating an XML schema from an annotated class, the JDK 1.8 schemagen correctly inserts a namespace prefix ("xs:") within the generated root schema element, implying that the standard _XmlSchema_ namespace is used. The corresponding element in JDK 9 and JDK 10 is emitted without the required namespace prefix, implying that the schema element belongs to the targetNamespace - which is incorrect.

This is a bug which actually prevents most tools to work properly. Since it was let through the process, I presume we have few integration tests to validate XSD generation. If you could point me to the correct place within the codebase, I could possibly supply a PR for this.

### JDK 1.8 execution: ###
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" targetNamespace="http://acme.com/customer-api" xmlns:tns="http://acme.com/customer-api" xmlns:xs="http://www.w3.org/2001/XMLSchema">
```

### JDK 9,10 execution:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<schema version="1.0" targetNamespace="http://acme.com/customer-api" xmlns:tns="http://acme.com/customer-api" xmlns:xs="http://www.w3.org/2001/XMLSchema">
```

**Comment by silkentrance** [comment]
Even for JDK9,10 it still reads ``xmlns:xs="http://www.w3.org/2001/XMLSchema"``. Did you c&p the wrong information?

**Comment by lennartj** [comment]
Nopes. The problem is that the xml namespace prefix (_xs:_) is not present on the _schema_ element when the schemagen tool of jdk 9 and 10 is run. That means that the _targetNamespace_ is used - and **that** implies that the schema element (and any child elements who need to be part of the standard XML schema namespace) are wrong.

**Comment by bravehorsie** [comment]
Please retest as suggested in #1220 so we can close this

**Comment by lukasj** [comment]
closing as per comments in #1220
