### ISSUE TITLE
Release job: replace sed with better tool when updating parent pom version

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#1229]
Issue #1219 contains note about temporary solution when updating parent POM version.

I was unable to make version plugin target update-parent working properly for this scenario so I used less reliable solution with sed filter rule.

It would be good to find better solution which will replace version string in specific xpath of POM file. Current sed filter doesnot understand XML structure and it just searches for specific version string to replace.

**Comment by lukasj** [comment]
I believe this is done
