### ISSUE TITLE
Build error on Jenkins: Could not transfer artifact org.apache.maven.plugins:maven-antrun-plugin:pom:1.8

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#1231]
Build jobs are failing with error:

`[ERROR] Plugin org.apache.maven.plugins:maven-antrun-plugin:1.8 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-antrun-plugin:jar:1.8: Could not transfer artifact org.apache.maven.plugins:maven-antrun-plugin:pom:1.8 from/to central (https://repo.maven.apache.org/maven2): Connection reset`

I'll downgrade plugin dependency to 1.7.

**Comment by Tomas-Kraus** [comment]
First there is copy-pasted version in several modules:
- xjc
- jxc
- docs/release-documentation

Last one is without version string and there is no version defined in parent poms!

Moving version to pluginManagement of project root pom/xml (jaxb-parent) which is common ancestor of all those 3 modules.

**Comment by Tomas-Kraus** [comment]
Checking build job logs again.
- https://jenkins.eclipse.org/jaxb-impl/job/jaxb-ri-ee4j8-build/1/consoleFull - version 1.8
`Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-antrun-plugin/1.8/maven-antrun-plugin-1.8.pom (3.3 kB at 38 kB/s)`
- https://jenkins.eclipse.org/jaxb-impl/job/jaxb-ri-ee4j8-build/2/consoleFull
`Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-antrun-plugin/1.8/maven-antrun-plugin-1.8.pom`
...and it failed with
`[ERROR] Plugin org.apache.maven.plugins:maven-antrun-plugin:1.8 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-antrun-plugin:jar:1.8: Could not transfer artifact org.apache.maven.plugins:maven-antrun-plugin:pom:1.8 from/to central (https://repo.maven.apache.org/maven2): Connection reset -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException`

**Comment by Tomas-Kraus** [comment]
This does not look like version 1.8 problem, but more like some issue in Jenkins CI itself.

**Comment by Tomas-Kraus** [comment]
pluginManagement problem is fixed in master.

**Comment by lukasj** [comment]
likely done
