### ISSUE TITLE
Outdated release documentation

### ISSUE THREAD

**Issue by GFriedrich** [eclipse-ee4j/jaxb-ri#1233]
The release documentation still mentions version 2.4.0, but as far as I can see the version was instead released as 2.3.1 (or is this an additional one inbetween?).
Also with version 2.3.1 jaxb-core was removed, but the jaxb-core.jar is still mentioned in the release notes, which makes it quite confusing. At least a hint should be added that the jaxb-core.jar was removed from 2.3.1 onwards.

**Comment by bravehorsie** [comment]
New JAXB site is published at https://eclipse-ee4j.github.io/jaxb-ri/
