### ISSUE TITLE
Implementation of JAXB-API has not been found on module path or classpath.

### ISSUE THREAD

**Issue by SebKister** [eclipse-ee4j/jaxb-ri#1235]
I am moving a project that uses the JPMS from Oracle JDK10 to OpenJDK11.
The app is compiling/running apart from any (un)marshaling operation using JAXB.
I am getting the following error:

**javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.**
 _- with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory]
	at java.xml.bind/javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:269)
	at java.xml.bind/javax.xml.bind.ContextFinder.find(ContextFinder.java:412)
	at java.xml.bind/javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:721)
	at java.xml.bind/javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:662)
	......
Caused by: java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.xml.bind/javax.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:122)
	at java.xml.bind/javax.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:155)
	at java.xml.bind/javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:267)
....._

I am importing through Maven the following libraries relevant to JAXB ( as :
**org.glassfish.jaxb:jaxb-runtime:2.4.0-b180830.0438
javax.xml.bind:jaxb-api:2.4.0-b180830.0359**

This are the requirements indicated in section 7.1.2 of the JAXB User Guide.
Am I missing something in my import or is there another issue ?

Thanks in advance.

**Comment by lukasj** [comment]
2.3.1 is the version to be used. 2.4.0-bxx are   usually just dev versions

**Comment by SebKister** [comment]
Thanks for your feedback.
I tried it with the release v2.3.1 and I am getting the same error.

**Comment by SebKister** [comment]
Here's a minimalistic project using IntelliJ as IDE. This works under Oracle JDK 10.0.2 and creates the same error as mentioned if using OpenJDK11

[demoJAXB.zip](https://github.com/eclipse-ee4j/jaxb-ri/files/2522186/demoJAXB.zip)

**Comment by SebKister** [comment]
I think the bug is here :

package javax.xml.bind;

class ContextFinder {
    private static final java.lang.String PLATFORM_DEFAULT_FACTORY_CLASS = "com.sun.xml_.internal._bind.v2.ContextFactory";
....
}

it should be "com.sun.xml.bind.v2.ContextFactory"

**Comment by lukasj** [comment]
This defines the default for what is in jdk8 (up to 10) and api still has to support that. I'd look more into how the service provider is defined in RI and if it gets registered properly on 11

**Comment by SebKister** [comment]
I tried the workaround but it is not solving the issue. I still get the ClassNotFoundException, althought this time with the class passed as parameter on the JVm (i.e. com.sun.xml.bind.v2.ContextFactory )
In my demo project removing  the module-info.java file fixes the problem ... but obviously that is not a solution for a JPMS based app. Thanks.

**Comment by SebKister** [comment]
That solved the issue. I hadn't noticed the change in the structure of the javax.xml.bind module but it makes perfect sens now. Thanks a lot !

**Comment by maddy24** [comment]
I am facing problem while migration of jdk11 as follows .xml.bind.JAXBException: Implementation of JAXB-API has not  - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
2019-03-18 10:32:02.500 [376] [W] [36805D6A45E342DEA3BAAE860F524CA7] [nfrastructure.cache.MemCachedHandlerImpl] | Exception
javax.xml.bind.DataBindingException: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
- with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
        at javax.xml.bind.JAXB.unmarshal(JAXB.java:230) ~[jakarta.xml.bind-api-2.3.2.jar!/:2.3.2]


added dependency in my module as follows 

<dependency>
			<groupId>javax.activation</groupId>
			<artifactId>javax.activation-api</artifactId>
		</dependency>

		<dependency>
			<groupId>org.glassfish.jaxb</groupId>
			<artifactId>jaxb-runtime</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.xml.bind</groupId>
			<artifactId>jaxb-api</artifactId>
		</dependency>
		<dependency>
			<groupId>com.sun.xml.bind</groupId>
			<artifactId>jaxb-core</artifactId>
		</dependency>
		<dependency>
			<groupId>com.sun.xml.bind</groupId>
			<artifactId>jaxb-impl</artifactId>
		</dependency>


root pom 

ndency>
				<groupId>javax.activation</groupId>
				<artifactId>javax.activation-api</artifactId>
				<version>1.2.0</version>
			</dependency>

			<dependency>
				<groupId>org.glassfish.jaxb</groupId>
				<artifactId>jaxb-runtime</artifactId>
				<version>2.3.2</version>
			</dependency>
			<dependency>
				<groupId>javax.xml.bind</groupId>
				<artifactId>jaxb-api</artifactId>
				<version>2.3.1</version>
			</dependency>
			<dependency>
				<groupId>com.sun.xml.bind</groupId>
				<artifactId>jaxb-core</artifactId>
				<version>2.2.11</version>
			</dependency>
			<dependency>
				<groupId>com.sun.xml.bind</groupId>
				<artifactId>jaxb-impl</artifactId>
				<version>2.2.11</version>
			</dependency>
		
lugin>
				<groupId>org.jvnet.jaxb2.maven2</groupId>
				<artifactId>maven-jaxb2-plugin</artifactId>
			</plugin>

**Comment by SebKister** [comment]
Did you put  "requires com.sun.xml.bind" in your module-info.java file ?

**Comment by bravehorsie** [comment]
@maddy24 There is no such class as `com.sun.xml.internal.bind.v2.ContextFactory` since JDK11. However this is tried as a last resort when no other implementation is found.

You should use either:
```
       <dependency>
		<groupId>org.glassfish.jaxb</groupId>
		<artifactId>jaxb-runtime</artifactId>
	</dependency>
```
or
```
        <dependency>
		<groupId>com.sun.xml.bind</groupId>
		<artifactId>jaxb-impl</artifactId>
	</dependency>
```
Not both of them.
Can you describe a bit more your execution environment (Is it in a webserver deploy, a JavaSE app, a Maven plugin) that is failing?

@SebKister 
`requires com.sun.xml.bind` is not necessary, `requires java.xml.bind` should be used instead, with `org.glassfish.jaxb:jaxb-runtime` on module path.

**Comment by bravehorsie** [comment]
`org.glassfish.jaxb:jaxb-runtime` is a thin jar with module-info provided. 
`com.sun.xml.bind:jaxb-impl` is a fat jar without module-info.

**Comment by lukasj** [comment]
also make sure you depend on:
```
	<dependency>
		<groupId>jakarta.xml.bind</groupId>
		<artifactId>jakarta.xml.bind-api</artifactId>
                <version>2.3.2</version>
	</dependency>
```

instead of `jaxb-api`, especially when your implementation is of version 2.3.2

**Comment by CHANDRAMOHANnegi** [comment]
`
	
<dependency>
    <groupId>javax.xml.bind</groupId>
    <artifactId>jaxb-api</artifactId>
    <version>2.3.0-b170201.1204</version>
</dependency>


<dependency>
    <groupId>javax.activation</groupId>
    <artifactId>activation</artifactId>
    <version>1.1</version>
</dependency>


<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-runtime</artifactId>
  
</dependency>`

**Comment by mirabilos** [comment]
@lukasj where is this documented (jakarta vs. jaxb-api)? I just see jaxb-api only has 2.3.1 while jaxb-impl has 2.3.2 and documentation is not forthcoming from search engines…

**Comment by lukasj** [comment]
@mirabilos https://wiki.eclipse.org/New_Maven_Coordinates ?

**Comment by mirabilos** [comment]
This (page only works with `s/\(http\)s/\1/` though) only lists changes, not the reason for them. Is this something Eclipse-specific? I’m trying to get some other projects to work with JDK 11 and need JAXB for them and 2.3.0 has bugs, so I’m trying to figure out upgrade instructions…

**Comment by mirabilos** [comment]
Hmm, doesn’t seem to be Eclipse-specific; the diff between http://central.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.3.1/jaxb-impl-2.3.1.pom and http://central.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.3.2/jaxb-impl-2.3.2.pom shows the same thing.

Thanks for your time, nevertheless!

**Comment by lukasj** [comment]
everything Java EE related will show the same - in case you didn't noticed: https://www.infoworld.com/article/3310042/eclipse-takes-over-all-java-ee-reference-components.html

**Comment by maheshd-techie** [comment]
-If anyone still facing the same issue then the below-given solution will perfectly work for them.

1. First add all these dependancies and plugin are in the pom.xml file:
============================================  
              <dependency>
			<groupId>javax.activation</groupId>
			<artifactId>javax.activation-api</artifactId>
			<version>1.2.0</version>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jaxb</groupId>
			<artifactId>jaxb-runtime</artifactId>
			<version>2.3.2</version>
		</dependency>
		<dependency>
			<groupId>javax.xml.bind</groupId>
			<artifactId>jaxb-api</artifactId>
			<version>2.3.1</version>
		</dependency>
		<dependency>
			<groupId>com.sun.xml.bind</groupId>
			<artifactId>jaxb-core</artifactId>
			<version>2.2.11</version>
		</dependency>

                <plugin>
			<groupId>org.jvnet.jaxb2.maven2</groupId>
			<artifactId>maven-jaxb2-plugin</artifactId>
		</plugin>

2. I am attaching the sample java example file and output file as well for your better understanding.

Java Standalone Class Example:
====================

package com.abc.xyz;

import java.io.File;
import java.util.Arrays;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
class User {

	private int id;
	private String name;
	private String email;
	private String[] roles;
	private boolean active;

	public User() {
	}

	public User(int id, String name, String email, String[] roles, boolean active) {
		super();
		this.id = id;
		this.name = name;
		this.email = email;
		this.roles = roles;
		this.active = active;
	}

	public int getId() {
		return id;
	}

	@XmlAttribute
	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	@XmlElement
	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return email;
	}

	@XmlElement
	public void setEmail(String email) {
		this.email = email;
	}

	public String[] getRoles() {
		return roles;
	}

	@XmlElementWrapper(name = "roles")
	@XmlElement(name = "role")
	public void setRoles(String[] roles) {
		this.roles = roles;
	}

	public boolean isActive() {
		return active;
	}

	@XmlElement
	public void setActive(boolean active) {
		this.active = active;
	}

	@Override
	public String toString() {
		return "User [id=" + id + ", name=" + name + ", email=" + email + ", roles=" + Arrays.toString(roles)
				+ ", active=" + active + "]";
	}
}

public class XmlFileReadWriteExample {

	public static void main(String[] args) {
		try {
			// To create XML file
			File file = new File("user.xml");

			// Getting the instance of `JAXBContext`
			JAXBContext context = JAXBContext.newInstance(User.class);

			// create an instance of `Marshaller`
			Marshaller marshaller = context.createMarshaller();

			// enable pretty-print XML output
			marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true);

			// Setting all the properties through the constructor
			User user = new User(1, "John Adams", "xyz@gmail.com", new String[] { "Admin", "HR" }, true);

			// here we are doing marshalling processing means converting Java Object to the
			// XML file
			marshaller.marshal(user, file);
		} catch (JAXBException e) {
			e.printStackTrace();
		}
	}
}

Sample Output File Contents:
==================
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<user id="1">
	<active>true</active>
	<email>xyz@gmail.com</email>
	<name>John Adams</name>
	<roles>
		<role>Admin</role>
		<role>HR</role>
	</roles>
</user>

**Comment by maheshd-techie** [comment]
-If anyone still facing the same issue then the below-given solution will perfectly work for them.

1. First add all these dependancies and plugin are in the pom.xml file:
============================================  
              `<dependency>
			<groupId>javax.activation</groupId>
			<artifactId>javax.activation-api</artifactId>
			<version>1.2.0</version>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jaxb</groupId>
			<artifactId>jaxb-runtime</artifactId>
			<version>2.3.2</version>
		</dependency>
		<dependency>
			<groupId>javax.xml.bind</groupId>
			<artifactId>jaxb-api</artifactId>
			<version>2.3.1</version>
		</dependency>
		<dependency>
			<groupId>com.sun.xml.bind</groupId>
			<artifactId>jaxb-core</artifactId>
			<version>2.2.11</version>
		</dependency>

                <plugin>
			<groupId>org.jvnet.jaxb2.maven2</groupId>
			<artifactId>maven-jaxb2-plugin</artifactId>
		</plugin>`

2. I am attaching the sample java example file and output file as well for your better understanding.

Java Standalone Class Example:
====================

`package com.abc.xyz;

import java.io.File;
import java.util.Arrays;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
class User {

	private int id;
	private String name;
	private String email;
	private String[] roles;
	private boolean active;

	public User() {
	}

	public User(int id, String name, String email, String[] roles, boolean active) {
		super();
		this.id = id;
		this.name = name;
		this.email = email;
		this.roles = roles;
		this.active = active;
	}

	public int getId() {
		return id;
	}

	@XmlAttribute
	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	@XmlElement
	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return email;
	}

	@XmlElement
	public void setEmail(String email) {
		this.email = email;
	}

	public String[] getRoles() {
		return roles;
	}

	@XmlElementWrapper(name = "roles")
	@XmlElement(name = "role")
	public void setRoles(String[] roles) {
		this.roles = roles;
	}

	public boolean isActive() {
		return active;
	}

	@XmlElement
	public void setActive(boolean active) {
		this.active = active;
	}

	@Override
	public String toString() {
		return "User [id=" + id + ", name=" + name + ", email=" + email + ", roles=" + Arrays.toString(roles)
				+ ", active=" + active + "]";
	}
}

public class XmlFileReadWriteExample {

	public static void main(String[] args) {
		try {
			// To create XML file
			File file = new File("user.xml");

			// Getting the instance of `JAXBContext`
			JAXBContext context = JAXBContext.newInstance(User.class);

			// create an instance of `Marshaller`
			Marshaller marshaller = context.createMarshaller();

			// enable pretty-print XML output
			marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true);

			// Setting all the properties through the constructor
			User user = new User(1, "John Adams", "xyz@gmail.com", new String[] { "Admin", "HR" }, true);

			// here we are doing marshalling processing means converting Java Object to the
			// XML file
			marshaller.marshal(user, file);
		} catch (JAXBException e) {
			e.printStackTrace();
		}
	}
}`

Sample Output File Contents:
==================
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<user id="1">
	<active>true</active>
	<email>xyz@gmail.com</email>
	<name>John Adams</name>
	<roles>
		<role>Admin</role>
		<role>HR</role>
	</roles>
</user>`

**Comment by maheshd-techie** [comment]
-If anyone still facing the same issue then the below-given solution will perfectly work for them.

1. First add all these dependancies and plugin are in the pom.xml file:
============================================  
              ```
                <dependency>
			<groupId>javax.activation</groupId>
			<artifactId>javax.activation-api</artifactId>
			<version>1.2.0</version>
		</dependency>

		<dependency>
			<groupId>org.glassfish.jaxb</groupId>
			<artifactId>jaxb-runtime</artifactId>
			<version>2.3.2</version>
		</dependency>

		<dependency>
			<groupId>javax.xml.bind</groupId>
			<artifactId>jaxb-api</artifactId>
			<version>2.3.1</version>
		</dependency>

		<dependency>
			<groupId>com.sun.xml.bind</groupId>
			<artifactId>jaxb-core</artifactId>
			<version>2.2.11</version>
		</dependency>

                <plugin>
			<groupId>org.jvnet.jaxb2.maven2</groupId>
			<artifactId>maven-jaxb2-plugin</artifactId>
		</plugin>
```

2. I am attaching the sample java example file and output file as well for your better understanding.

Java Standalone Class Example:
====================

package com.abc.xyz;

import java.io.File;
import java.util.Arrays;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
class User {

	private int id;
	private String name;
	private String email;
	private String[] roles;
	private boolean active;

	public User() {
	}

	public User(int id, String name, String email, String[] roles, boolean active) {
		super();
		this.id = id;
		this.name = name;
		this.email = email;
		this.roles = roles;
		this.active = active;
	}

	public int getId() {
		return id;
	}

	@XmlAttribute
	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	@XmlElement
	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return email;
	}

	@XmlElement
	public void setEmail(String email) {
		this.email = email;
	}

	public String[] getRoles() {
		return roles;
	}

	@XmlElementWrapper(name = "roles")
	@XmlElement(name = "role")
	public void setRoles(String[] roles) {
		this.roles = roles;
	}

	public boolean isActive() {
		return active;
	}

	@XmlElement
	public void setActive(boolean active) {
		this.active = active;
	}

	@Override
	public String toString() {
		return "User [id=" + id + ", name=" + name + ", email=" + email + ", roles=" + Arrays.toString(roles)
				+ ", active=" + active + "]";
	}
}

public class XmlFileReadWriteExample {

	public static void main(String[] args) {
		try {
			// To create XML file
			File file = new File("user.xml");

			// Getting the instance of `JAXBContext`
			JAXBContext context = JAXBContext.newInstance(User.class);

			// create an instance of `Marshaller`
			Marshaller marshaller = context.createMarshaller();

			// enable pretty-print XML output
			marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true);

			// Setting all the properties through the constructor
			User user = new User(1, "John Adams", "xyz@gmail.com", new String[] { "Admin", "HR" }, true);

			// here we are doing marshalling processing means converting Java Object to the
			// XML file
			marshaller.marshal(user, file);
		} catch (JAXBException e) {
			e.printStackTrace();
		}
	}
}

Sample Output File Contents:
==================
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<user id="1">
	<active>true</active>
	<email>xyz@gmail.com</email>
	<name>John Adams</name>
	<roles>
		<role>Admin</role>
		<role>HR</role>
	</roles>
</user>

```

**Comment by mirabilos** [comment]
Nope.

It’s either…

                        <dependency>
                                <groupId>com.sun.activation</groupId>
                                <artifactId>jakarta.activation</artifactId>
                                <version>${activation.version}</version>
                        </dependency>

… or, if you don’t need the impl, `jakarta.activation-api` now, though use only one of them, e.g. like this:

                        <dependency>
                                <groupId>jakarta.xml.bind</groupId>
                                <artifactId>jakarta.xml.bind-api</artifactId>
                                <version>${jaxb-api.version}</version>
                                <exclusions>
                                        <exclusion>
                                                <groupId>jakarta.activation</groupId>
                                                <artifactId>jakarta.activation-api</artifactId>
                                        </exclusion>
                                </exclusions>
                        </dependency>

**Comment by lukasj** [comment]
Don’t use activation-api (and make sure it’s removed from all paths) if you want JPMS. That combination is not going to work

**Comment by mirabilos** [comment]
Lukas Jungmann dixit:

>Don’t use activation-api (and make sure it’s removed from all paths) if
>you want JPMS. That combination is not going to work

I don’t even know what JPMS is but jaxb-* depends on activation.

bye,
//mirabilos
-- 
tarent solutions GmbH
Rochusstraße 2-4, D-53123 Bonn • http://www.tarent.de/
Tel: +49 228 54881-393 • Fax: +49 228 54881-235
HRB 5168 (AG Bonn) • USt-ID (VAT): DE122264941
Geschäftsführer: Dr. Stefan Barth, Kai Ebenrett, Boris Esser, Alexander Steeg

**Comment by lukasj** [comment]
JPMS stands for Java Platform Module system.

I’ve said that ‘-api’ artifact is the one not to be used at runtime. I haven’t said that no activation jar should be present.

**Comment by mirabilos** [comment]
Lukas Jungmann dixit:

>JPMS stands for Java Platform Module system.

OK… http://www.mirbsd.org/wtf.cgi?q=JPMS told me the same,
doesn’t mean I now know more than before.

>I’ve said that ‘-api’ artifact is the one not to be used at runtime. I
>haven’t said that no activation jar should be present.

Right but it’s apparently a compile scope dependency (and
thus also runtime) of some other Jakarta projects…

bye,
//mirabilos
-- 
tarent solutions GmbH
Rochusstraße 2-4, D-53123 Bonn • http://www.tarent.de/
Tel: +49 228 54881-393 • Fax: +49 228 54881-235
HRB 5168 (AG Bonn) • USt-ID (VAT): DE122264941
Geschäftsführer: Dr. Stefan Barth, Kai Ebenrett, Boris Esser, Alexander Steeg

**Comment by nihatonder** [comment]
If you still have this problem, you can check the following link. Also, I added a working soap service example with java 11.
https://medium.com/@nihatonder87/java-11-soap-service-resolving-issues-4e78d21b1aa3

**Comment by AayushiChauhan152** [comment]
I'm still getting the same error.I have already included all the above mentioned dependencies.

**Comment by nihatonder** [comment]
Hi,
Have you tried to run the example project in the github link?
https://github.com/nihatonder/soap-service-java-11
