### ISSUE TITLE
Use of non modular javax.activation-api:1.2.0 block deployment through JLink

### ISSUE THREAD

**Issue by SebKister** [eclipse-ee4j/jaxb-ri#1236]
Both javax.xml.bind:jaxb-api:2.3.1 and org.glassfish.jaxb:jaxb-runtime:2.3.1 use javax.activation-api-1.2.0.jar which does not contain a module-info file thus causing an error when used with jlink who doesn't allow automatic module. It is not clear if this will be a problem with futur packaging tool of JEP 343.

**Comment by lukasj** [comment]
there is no javax.activation-api with module-info available yet

**Comment by SebKister** [comment]
Indeed, but this is unfortunately blocking the transition of my app towards JDK11. 
A bit annoying that javax.xml.bind got removed from the jdk without having a solution ready to support projects that made the (big...) step to move to JPMS with JDK 9.... Anyway thanks for your help !

**Comment by bravehorsie** [comment]
Unfortunately there is no better support for javax.activation-api than `Automatic-Module-Name: java.activation` in a manifest file. However this does not prevent JAXB to work with JDK 11 from module path. If you need for some reason not to use automatic module, you always have an option to put any subset of problematic jars on classpath. There is no other way around it until all dependencies have native module descriptors.

**Comment by lukasj** [comment]
Transition to jakarta makes this even more difficult to solve now as maven coordinates will change and discussions about module names we should use is still opened - see https://github.com/eclipse-ee4j/ee4j/issues/34 and https://github.com/eclipse-ee4j/ee4j/issues/35 for details. I'm thinking whether we could provide JDK10-like module to provide smoother transition path through the turbulent times, ie an artifact which would contain RI + dependencies which are not yet proper JPMS modules, so those who need jlink have some option, or possibly jmod artifact. @bravehorsie what do you think?

**Comment by bravehorsie** [comment]
Lets examine what those "non-proper" jars are, I believe there are not many. Overall it sounds good and may be convenient for some users, but the problem to have in mind with fat or partially "not in shape" jars is that other libraries in same JVM can bring classes from such repackaged modules as an unnamed or other modules which than will cause split package problem with JAXB module. That said if we provide such jar we should warn users bold on using it.

Current state of JAXB modularization is trying to be as separated as possible down to individual maven artefacts of each dependency. While usage of automatic modules is not optimal and is considered to be a "transition step" it is well defined by JPMS and does not cause any issues which should prevent from using them. [Here is the reason and workaround](http://mail.openjdk.java.net/pipermail/jigsaw-dev/2016-July/008559.html) why jlink doesn't allow automatic modules.

**Comment by SebKister** [comment]
I would personally favor lukasj proposition of creating JDK10-like module which would contain RI + dependencies which are not yet proper JPMS modules, and assume clearly that this is a transition solution for jlink which IMHO should not be neglected especially now (java 11) that you can't rely on a preexisting JRE. Meanwhile I will have a look at the use of jdep -geninfo +injection to solve my issue.

**Comment by SebKister** [comment]
I followed Remi Forax's suggestion of using jdeps --generate-module-info ... but this led to missing dependencies blocking the creation of a module-info.
PS C:\Program Files\Java\jdk-11\bin> .\jdeps.exe  --generate-module-info E:\temp E:\temp\javax.activation-api-1.2.0.jar
Missing dependence: E:\temp\java.activation\module-info.java not generated
Error: missing dependencies
   javax.activation.MailcapCommandMap                 -> com.sun.activation.registries.LogSupport           JDK removed internal API
   javax.activation.MailcapCommandMap                 -> com.sun.activation.registries.MailcapFile          JDK removed internal API
   javax.activation.MimetypesFileTypeMap              -> com.sun.activation.registries.LogSupport           JDK removed internal API
   javax.activation.MimetypesFileTypeMap              -> com.sun.activation.registries.MimeTypeFile         JDK removed internal API

and if done with jdeps in JDK 10 we get ( without surprise ...) a split package issue.
I don't see a clear work around for that.

**Comment by lukasj** [comment]
If you don't insist on final artifacts, browse this repo: https://oss.sonatype.org/content/groups/staging/com/sun/activation/ - big warning: what you see there is not final release (as url says - it's some staging repo)

**Comment by SebKister** [comment]
Well that did do the trick! I can move forward from here and will use that version at least for beta testing. 
Thanks a lot for your support.

Attached the modularized jar.
[javax.activation-1.2.1-20181010.205421-2_modular.jar.zip](https://github.com/eclipse-ee4j/jaxb-ri/files/2532373/javax.activation-1.2.1-20181010.205421-2_modular.jar.zip)
