### ISSUE TITLE
Release to OSSRH staging repository

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jaxb-ri#1237]
- [x] Uptake new Eclipse versions of dependencies. Use [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) wiki to find components versions to use.

- [x] Release to OSSRH staging repository

- [x] Update [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) with released version number. 

[How to release first versions of EE4J components](https://wiki.eclipse.org/How_to_release_first_versions_of_EE4J_components)

**Comment by mkarg** [comment]
@Tomas-Kraus Can you please stage this to OSSRH? JAX-RS essentially needs this to run its tests, so we cannot stage without. Thanks.

**Comment by Tomas-Kraus** [comment]
We must prepare dependencies first. But we are working hard on getting jaxb-ri to staging.

**Comment by lukasj** [comment]
currently blocked by the fact that jakarta.activation:1.2.1 disappeared from staging. As soon as it appears there again, this can be completed as all preparation work has been already finished, it is just a build of jaxb-fi and jaxb-ri which are pending

**Comment by mkarg** [comment]
JAX-RS decided to not compile against JDK11, so we can stage without this dependency. Hope this loweres the pressure on this issue. :-)
