### ISSUE TITLE
Java 11 compatibility of the library jaxb-impl

### ISSUE THREAD

**Issue by bhalgatneha** [eclipse-ee4j/jaxb-ri#1272]
Could you help us by answering the following questions:

Library Name:
Latest version: <latest 1.1.1="" eg:="" version.="">
Latest version Is the library compatible with Java 11 Compatible? (Y/N)
Is the library supported with Java 11? (Y/N)
(If “N” in compatibility or support) What is the versions that would be compatible and Supported?
Date of support availability?
Is it recommended to use jaxb-runtime instead of jaxb-impl?

**Comment by bravehorsie** [comment]
Both `org.glassfish.jaxb:jaxb-runtime` and `com.sun.xml.bind:jaxb-impl` starting from version 2.3.2 supports JavaSE 11. `jaxb-runtime` is intended to be used in JavaSE environment either on module path as JPMS module or on the classpath. `jaxb-impl` is intended to be used in an osgi environment such as GlassFish.

**Comment by seelmann** [comment]
Is version 2.3.2 already available? 
Release tag exists: https://github.com/eclipse-ee4j/jaxb-ri/releases/tag/2.3.2-RI
But I cannot find the artifacts in Maven central. Also the project download page is empty: https://projects.eclipse.org/projects/ee4j.jaxb/downloads
