### ISSUE TITLE
xjc.bat (and schemagen.bat) fails for version >2.3.0 (JDK11)

### ISSUE THREAD

**Issue by normann1974** [eclipse-ee4j/jaxb-ri#1273]
To make JAXB work in JDK 11, I've read that I need jaxb-ri >2.3.0, so I downloaded jaxb-ri-2.3.1.zip. but xjc.bat fails due to classpath errors.

```
Java major version: 11
Error occurred during initialization of boot layer
java.lang.module.FindException: Module com.sun.tools.rngdatatype not found, required by com.sun.tools.xjc
```

To make it work, I changed the following line

```
set JAXB_PATH=%JAXB_HOME%/mod/jaxb-xjc.jar;%JAXB_HOME%/mod/jaxb-api.jar;%JAXB_HOME%/mod/codemodel.jar;%JAXB_HOME%/mod/jaxb-runtime.jar;%JAXB_HOME%/mod/istack-commons-runtime.jar;%JAXB_HOME%/mod/istack-commons-tools.jar;%JAXB_HOME%/mod/rngom.jar;%JAXB_HOME%/mod/xsom.jar;%JAXB_HOME%/mod/dtd-parser.jar;%JAXB_HOME%/mod/txw2.jar;%JAXB_HOME%/mod/stax-ex.jar;%JAXB_HOME%/mod/FastInfoset.jar;%JAXB_HOME%/mod/javax.activation.jar;%JAXB_HOME%/lib/relaxngDatatype.jar
```

into

```
set JAXB_PATH=%JAXB_HOME%/mod/jaxb-xjc.jar;%JAXB_HOME%/mod/jaxb-api.jar;%JAXB_HOME%/mod/codemodel.jar;%JAXB_HOME%/mod/jaxb-runtime.jar;%JAXB_HOME%/mod/istack-commons-runtime.jar;%JAXB_HOME%/mod/istack-commons-tools.jar;%JAXB_HOME%/mod/rngom.jar;%JAXB_HOME%/mod/xsom.jar;%JAXB_HOME%/mod/dtd-parser.jar;%JAXB_HOME%/mod/txw2.jar;%JAXB_HOME%/mod/stax-ex.jar;%JAXB_HOME%/mod/FastInfoset.jar;%JAXB_HOME%/mod/javax.activation-api.jar;%JAXB_HOME%/mod/relaxng-datatype.jar
```

The name of the `javax.activation-api.jar` file was corrected, and the path and name of the `relaxng-datatype.jar` file was corrected.

The `lib` folder (that existed in earlier JAXB releases) is also referenced in this line:

`if exist "%JAXB_HOME%\lib\jaxb-xjc.jar" goto CHECKJAVAHOME`

which should probably also be fixed. From what I can see, the problems still existing on the 2.3.2 branch, therefore this issue.

**Comment by lukasj** [comment]
EE4J_8 or actual binaries from ossrh staging repo are source of truth

**Comment by lukasj** [comment]
Ah, windows... @bravehorsie can you take a look, please?
