### ISSUE TITLE
Removed previous tarball jaxb-ri 2.3.2-RELEASE

### ISSUE THREAD

**Issue by wltjr** [eclipse-ee4j/jaxb-ri#1275]
Not sure what happened, but seems the last 2.3.2-RELEASE was removed and new tags were added per package or something. Can the previous tag be restored? This broke several Gentoo ebuild packages that were using those sources. I am not sure if the 2.3.2-RI tag/tarball is the same as the now removed 2.3.2-RELEASE.

It is really bad to remove tags once created. More so when they are marked with RELEASE. I understand much of this is in flux at the moment, but please watch out for such. Thank you!

**Comment by lukasj** [comment]
There is no official 2.3.2 release yet and whatever tag was created, was wrong. Once   2.3.2 release is announced, tag (2.3.2) won't change, till then, content of the tag may change at any time

**Comment by wltjr** [comment]
What is the explanation for the 4 tags created today?

There was a release tarball tagged 2.3.2-RELEASE. That tag was removed, along with the Initial import tag that most repositories from Oracle have. I have been monitoring the packages that Oracle donated in this issue https://github.com/Obsidian-StudiosInc/os-xtoo/issues/61. If you look at any of those they most all have a tag from the initial import, and also a version-RELEASE tag, though some are just version without -RELEASE.

If you look you will see 9 days ago I updated several jaxb-ri based packages, and codemodel 8 days ago. Since then that tarball was removed and 4 others added today.
```
wltjr added a commit that referenced this issue 9 days ago
@wltjr
dev-java/rngom: Bump 2.3.1 -> 2.3.2, new upstream, swap dep
208453a
wltjr added a commit that referenced this issue 9 days ago
@wltjr
dev-java/txw2: Bump 2.3.1 -> 2.3.2, new upstream
abe0f4f
wltjr added a commit that referenced this issue 9 days ago
@wltjr
dev-java/jaxb-runtime: Bump 2.3.1 -> 2.3.2, new upstream
78ceae8
wltjr added a commit that referenced this issue 9 days ago
@wltjr
dev-java/jaxb-xsom: Bump 2.3.1 -> 2.3.2, new upstream, swap dep
597ced6
wltjr added a commit that referenced this issue 9 days ago
@wltjr
dev-java/jaxb-xjc: Bump 2.3.1 -> 2.3.2, new upstream
02c1c24


wltjr added a commit that referenced this issue 8 days ago
@wltjr
dev-java/codemodel: Bump 2.7 -> 2.3.2, new upstream
16b0e1b 
```

**Comment by wltjr** [comment]
Not sure what is going on with eclipse-ee4j project, but I am noticing changes on other projects as well like https://github.com/eclipse-ee4j/saaj-api/issues/27. I have others that failed to download on another server, which means they likely changed as well.

Sadly I deleted my local copy of the now MIA jaxb-ri 2.3.2-RELEASE.tar.gz. Thankfully I still have others for any others that changed or got re-tagged. I will just have to use the tarballs I downloaded for now, till I can figure out what is going on with eclipse-ee4j. I have not seen this with other Eclipse projects, and I have packaged some 80+ in my [Gentoo overlay](https://github.com/Obsidian-StudiosInc/os-xtoo/tree/master/dev-java). Eventually will need to move eclipse-* packages to other categories if they continue to grow, like if I go to package the rest of Eclipse IDE.

**Comment by lukasj** [comment]
https://www.eclipse.org/lists/ee4j-pmc/msg01541.html should give you some background. Once binaries become available to public in mvn central, corresponding tag won't change.

**Comment by wltjr** [comment]
@lukasj this is creating a huge mess. I am seeing more and more now not have the -RELEASE tag. I guess I need to switch all those over. While others like [Jersey](https://github.com/eclipse-ee4j/jersey/releases) retain the -RELEASE tag at least for now.

Can you all at Eclipse please get things together? Can the previously created tags be restored or something? Or not remove the new tags without the -RELEASE. I have never seen such with any other projects. Surely not Java EE stuff.

I spent considerable time on this already. Which it seems now I have to repeat due to the superficial changes. I would have thought the whole how to tag a release would have been resolved before projects started getting tagged.

**Comment by lukasj** [comment]
Who, where and when announced that all ee4j subprojects were released and are available for public use? Some of them are but definitely not all of them. Ie metro-jaxws-ri or metro-wsit has even not passed all required reviews, so one is on the very thin ice when relying on any tag within these projects at least and any usage is at own risk.

**Comment by wltjr** [comment]
@lukasj adding a tag that is suffixed with -RELEASE is such an announcement. Who created those tags? Are you blaming me for paying attention to the repository and using tags that are marked with -RELEASE? There was time between the initial-contribution tag and the -RELEASE tag. Yes I assumed it was an released version, as the tag was marked as such.

These were not -rc, -pre, or other tags that would denote that a release is coming but this is not there yet. Like [Jersey has now](https://github.com/eclipse-ee4j/jersey/releases) with adding -RC plus -RELEASE.... What about [glassfish-hk2](https://github.com/eclipse-ee4j/glassfish-hk2/releases), it had a b as in beta release from upstream that was created after the initial-contribution tag, and then another -RELEASE tag after that. Why are you all creating these tags people should not use and rely upon?

What is the reasoning behind the other project tags changing from version-RELEASE to just version? Are those not to be used either? The fact tags exist without beta, alpha, pre, rc, or other normal identifiers tells others these are release tags.

So what are the current tags for jaxb-ri created today? Are those release tags or tags created for no purpose. No one should use those tags/tarballs?

Please do not blame me, I am simple trying to package this stuff. Most of which I had packaged using Oracles respositories. I am just switching the upstream. Which in less than a month has created a whole other mess. Which it seems I am to blame for?

**Comment by wltjr** [comment]
What metro-jaxws-ri are you talking about? Are you speaking of [metro-jax-ws](https://github.com/javaee/metro-jax-ws) that Oracle has not archived? Or some other?

It looks like the initial-contribution tag was also removed from metro-wsit, which has a [2.4.3 tag](https://github.com/eclipse-ee4j/metro-wsit/releases) created 6 days ago. What is the purpose of that tag? Is that a release tag? It has no other suffix, so most would normally assume it is a release version.

**Comment by lukasj** [comment]
First - I'm not blaming anyone for anything - definitively not at midnight during my time off. >90% people behind ee4j are on their vacation this week. There are no robots nor androids there other than jenkins. It's good people are watching but it should be also understood that things may be changing before initial release gets officially announced for public use. Not all and every person knows that having a tag ending with '-RELEASE' means official release. Have you seen those used in all original repos?

Second - nobody I know is able to do everything right on the first go, especially when it comes to >5m LOC spread through 50+ repositories. There is no match between Java EE and EE4J infrastructure, so things are being tuned on the go, bugs are being discovered during testing and fixes to staged artifacts (those tagged as supposed to be final) needs to be delivered. It will settle down after the initial release.

Metro-jax-ws is supposed to be archived, it is just not marked as such yet since issues need to be transferred first (same for metro-wsit) I believe. 

wsit 2.4.3 is supposed to be final version currently under testing, the content of this tag is going to change at least once in the next 2 weeks since there are still few issues which needs to be fixed in its dependencies.

**Comment by wltjr** [comment]
Ok, I read the link you provided, and one thing is clear. Those ARE release tags. Per the [link](https://www.eclipse.org/lists/ee4j-pmc/msg01541.html) it clearly says

"When we discussed this recently the consensus was that release tags should be git annotated tags that use the release number as the tag name."

Which means those are release tags, announced or not. Or they should not be tagged or tagged otherwise. That entire post is discussion the release on Github.

I have not seen the -RELEASE tag used anywhere but in eclipse-ee4j projects. Which seems despite people being away on vacation etc. Someone did today re-create many of those tags. In that process the -RELEASE tags were removed. I care less about which format. But these are newly created tags, and newly replaced tags. Someone is doing something, I doubt that is automated.

I have no problem with mistakes, but why remove the other tags? They are cheap. This came up with Netbeans for 9.0, where the tag in Github had a -vc suffix. It took sometime but they just created another tag 9.0 stand alone. The same thing happened for 10.0. You can see all those tags, and some point to the same commit. Tags are cheap, thus IMHO the incorrect ones should have been left and correct ones added. The -RELEASE ones not removed, just others added. My gripe in removing tags that once existed. Not if they should have existed, or what format. Just that they were there and now gone causing me to do more work. It would have been less work to leave those tags.

When Oracle marks them as archived, usually the new repo has a tag of iniitial-contribution. That tag has been removed from some repositories like this one and others that replaced the -RELEASE tag with a version. That is moot, but others are retaining that initial-contribution tag, and is just another example of deviation. But again why would anyone remove that tag? It only costs Github in hosting a binary, no one else.

If possible you all should discuss the tagging process. Any tag with a version that does not have a suffix like alpha, beta, rc, pre, etc is likely going to be assumed a release version. Even the discussion linked calls them releases. It seems maybe some were created prematurely. Still no explanation for the new tags created in this repo today, replacing the other tag, all with the same 2.3.2 versions, just different prefixes and suffixes.

I think I have most worked out for now. Till others drop the -RELEASE and/or other stuff. For a few the tag did not change, but the tag was re-pushed so the tarball of the sources changed. Which caused me to have to update the packages manifest and tarball digest. I had a [bunch of commits today](https://github.com/Obsidian-StudiosInc/os-xtoo/commits?author=wltjr&since=2018-12-27&until=2018-12-28) due to this chaos with tags. I had other things to work on as I am sure you do as well :)

**Comment by wltjr** [comment]
FYI that 2.3.2-ri tag was re-created today. The other 3 tags remain as they did the other day, 6 days ago. Not sure why someone deleted and re-created the same tag. Really bad tagging practices going on. Really bad to delete a tag. Really bad to re-create a tag. The only time it is okay to do such is right after a tag was created. Once a few days pass, the tag should be left alone and new ones created.

**Comment by wltjr** [comment]
I just do not understand the need to delete and re-create tags rather than leaving them as is and creating other tags. I really have never seen a public project do such with tags before. Hoping it is just this repo and not other ee4j repos

**Comment by lukasj** [comment]
It's ~40% of repos since it's done by 1 person taking care of build/release jobs. Not all repos are changing, mostly only those where blocking bugs are found during testing

**Comment by wltjr** [comment]
Is it at all possible to get them to not delete tags? I re-digested some others, and may have to again if the tag was changed. I did not update the jaxb-ri packages, though I think I can use that 2.3.3-ri tag that was  deleted and re-created today. If I did, I would have had to redigest. Or switch back to Oracle repos till the next release.

My gripe is just with deleting tags, and for some also creating new ones in some repos the same as the deleted one. Which produces the same tarball filename, but with a different size, so it breaks any digest/hash. Then I have to re-create the digest/manifest, which just waste time.

**Comment by lukasj** [comment]
I can pass them a fix for https://wiki.eclipse.org/JakartaEE_New_Infra_Release_Job if you provide it..

**Comment by wltjr** [comment]
So that is the problem, it only has support for release and snapshot nothing in between it seems. I further assume you all are testing out a release, and since that does not allow usage of say alpha, beta, rc, etc. Then all you can do is re-use the same numbers over and over. Rather shocking who ever produced such or worked on it did not take into consideration at least release candidates or something for testing.

Thanks for pointing that out! If it continues to occur and annoys me enough I may look into addressing the issue. Hopefully someone else does that is part of the project and/or it becomes unnecessary at some point soon.

**Comment by bravehorsie** [comment]
It is inappropriate concept on how to make a first EE4J release rather than lack of code supporting release candidates or other beta versions.

**Comment by Tomas-Kraus** [comment]
@wltjr Well, simply accept the fact that things work this way now. We had to migrate everything in quite short time and there was not enough time to implement everything the way it should be.
If you have time and knowledge to implement perfect release ingeneering for >50 projects in 3 weeks, you can give it a try. If not, please stop this useless flame war. We have more urgent tasks to do now.

**Comment by wltjr** [comment]
@Tomas-Kraus I do and have, but it was an odd way to start things out for enterprise level projects. I understand the amount of work, time frame, etc, Why after seeing the script and understanding the root of the problem, I backed off. This is not a flame war, it was something that caused many packages in my overlay to break. Ones I had just spent time working on. I think most people would find such frustrating. More so that any fix at the time, might need another fix, till things were officially released.

Now that it has been released. I assume the 2.3.2-RI tag is the main one. That tag replaces the previous 2.3.2-RELEASE tag. That format is not really consistent with other ee4j projects, but is moot. Will 2.3.3, or 2.4.x also have the -RI suffix or not?

I need to reliably be able to fetch source tarballs based on a tag, a tag that does not change or get removed, nor the format of the tag change. On occasion is understandable. But it has already gone from 2.3.2-RELEASE to 2.3.2-RI, and if it changes to just 2.3.2 or something in the future. That will be a fair amount of format changes in short period of time. It makes things difficult for others. I maintain thousands of Java packages. I only take my time to comment on things like this when they really matter.

Please do not delete tags! Please keep consistent tag format for future releases! Do those two things and you will never hear from me on such topics. Thank you very much!

**Comment by Tomas-Kraus** [comment]
JAXB RI structure changed a bit during transition to Eclipse and current release process is not final. Hope I'll be able to do all 4 components release in a single shot having just a single tag for each release. Also we'll have beta/RC/final releases without moving the tag next time.
Proper release tags should be just release version in the future without "-RI".

**Comment by Tomas-Kraus** [comment]
Also you may wait a bit with consuming Jakarta EE in other projects. At least until Glassfish is released and all this madness will be over. Doing it now is quite risky.

**Comment by wltjr** [comment]
Ok thanks for the heads up. I do also care about project structure as I create several packages from the same tag/tarball. If there are going to be individual tarballs and different tags for the subprojects that would effect my packaging efforts. Either way I will hold off for further action, or at least now aware of upcoming potential changes, and the current status being in flux. Thank you for the information!
