### ISSUE TITLE
jakarta.activation-api should not be used at runtime

### ISSUE THREAD

**Issue by HansBrende** [eclipse-ee4j/jaxb-ri#1284]
According to the comments on one [JAF issue](https://github.com/eclipse-ee4j/jaf/issues/18):

> The activation-api artifact... [is] not intended to be used at runtime. Any artifacts that are used at runtime should not depend on activation-api.

> The javax.activation API classes depend on the com.sun.activation implementation classes, and vice versa. There isn't the same API/implementation split that you find in some other projects.

So, doesn't this mean that either (1) jakarta.activation-api should have `provided` scope, or (2) it should be replaced with `com.sun.activation:jakarta.activation`?

This issue has led to numerous `NoClassDefFoundError` headaches for `com.sun.activation` classes, e.g., in [Apache Tika](https://issues.apache.org/jira/browse/TIKA-2778). The only workaround has been to manually exclude `activation-api` from `jaxb-runtime` and add an extra dependency on `com.sun.activation:jakarta.activation`. (Since `activation` *duplicates* all the code in `activation-api`, rather than *depending on* `activation-api`, merely adding the extra dependency doesn't suffice--the exclusion is necessary to avoid duplicate class names.)

Surely this rigmarole isn't intended?

**Comment by bravehorsie** [comment]
Interesting, I didn't know that activation implementation bundles API classes instead of depending on it. Both JAXB-RI and JAXB-API has a dependency to activation. Depending on different artifacts for each of them would not work on JPMS, on the other hand it is not good for JAXB-API to have a dependency on activation implementation.

**Comment by HansBrende** [comment]
@bravehorsie Why would it not be good for JAXB-API to have a dependency on `jakarta.activation`? There are only 10 extra classes that would be included by using `jakarta.activation`, and as @bshannon mentioned, this is not the "implementation" per se, but rather, utility classes on which the actual implementation depends, and therefore should not be excluded at runtime.

If JAXB-API depending on `jakarta.activation` is really a non-starter, then I would suggest the following change: 

1. Have JAXB-API depend on `jakarta.activation-api` with `provided` scope. 
2. Have JAXB-RI depend on `jakarta.activation` with `compile` scope.

**Comment by bshannon** [comment]
If the JAXB-API jar file is intended to be used at runtime, it needs to depend on other artifacts
that are intended to be used at runtime - that means jakarta.activation, not jakarta.activation-api.

**Comment by lukasj** [comment]
jaxb-api.jar is supposed to be put to endorsed folder as it may be newer (or older) than the one provided by JDK and AFAIK runtime classes do not belong there. Having runtime classes there can lead to various classloading related issues further down the road.

**Comment by bshannon** [comment]
There's no such restriction on the endorsed directory.

Putting a new JAXB API jar file there without also including a JAXB implementation
of the new JAXB API seems like a bigger issue.  You don't want to use the old
implementation with the new APIs.

**Comment by lukasj** [comment]
If I want to get a security fix in API before it gets to the official JDK build I don't need new RI implementation. Also note that implementation packages are different in JDK and in standalone implementation.

**Comment by bshannon** [comment]
Ok, yes, you're right, if the actual *API* hasn't changed, you can put a newer
API jar file in the endorsed directory without updating the implementation classes.
And as the endorsed standards document you linked to in your edited message
above states, you *can* put implementation classes in the endorsed directory.

But this discussion seems to be off-topic for this issue.

**Comment by bravehorsie** [comment]
@HansBrende Technically it would work, but generally APIs shouldn't have dependency to implementation classes by design. JAXB-API doesn't use any of additional classes in `jakarta.activation` implementation and you can't use JAXB-API alone in runtime without a JAXB implementation, so dependency to `jakarta.activation` API seems to be correct here.
