### ISSUE TITLE
Version 2.3.2 not available in Maven Central yet

### ISSUE THREAD

**Issue by Sanne** [eclipse-ee4j/jaxb-ri#1297]
I noticed version `2.3.2` was released more than a month ago, but it's not available for people to use via Maven yet:
 - https://repo.maven.apache.org/maven2/javax/xml/bind/jaxb-api/

**Comment by pzygielo** [comment]
Perhaps, as presented in [New Maven Coordinates](https://wiki.eclipse.org/New_Maven_Coordinates) you shall look for https://repo.maven.apache.org/maven2/jakarta/xml/bind/jakarta.xml.bind-api/2.3.2?

**Comment by m0mus** [comment]
Closing

**Comment by Sanne** [comment]
Many thanks. May I suggest to advertise this change? We just god used to the "new coordinates" now they changed again.

In particular the old JAXB website(s) could more prominently highlight the project was moved multiple times, when googling around it took me a long time just to find the right homepage & issue tracker.

Also, when changing groupId on a project it is good practice to publish a redirection artifact.
 - https://maven.apache.org/guides/mini/guide-relocation.html
