### ISSUE TITLE
Module reads package javax.activation from both java.activation and jakarta.activation

### ISSUE THREAD

**Issue by highsource** [eclipse-ee4j/jaxb-ri#1298]
When I'm trying to build the project under Java 10 I ultimately get the following error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project jaxb-runtime: Compilation failure: Compilation failure: 
[ERROR] error: module org.jvnet.staxex reads package javax.activation from both java.activation and jakarta.activation
[ERROR] error: the unnamed module reads package javax.activation from both jakarta.activation and java.activation
[ERROR] error: module jakarta.activation reads package javax.activation from both jakarta.activation and java.activation
```

Attached the complete `mvn clean install` log:

[std.txt](https://github.com/eclipse-ee4j/jaxb-ri/files/2985246/std.txt)

**Comment by highsource** [comment]
Same as eclipse-ee4j/jaxb-stax-ex#21.

**Comment by highsource** [comment]
`runtime` compiles under Java 11 (tried 11.0.1).

**Comment by lukasj** [comment]
one needs either JDK 11 or JDK 8

**Comment by highsource** [comment]
Maye put a note about this in `HOWTO-build.txt`?

**Comment by bravehorsie** [comment]
I will update a README.md with build instructions.

**Comment by kimvdmeulen** [comment]
I had the same issue - had to delete the glassfish server dependency from the Client
