### ISSUE TITLE
Module not found: resolver

### ISSUE THREAD

**Issue by highsource** [eclipse-ee4j/jaxb-ri#1300]
Similar to #1299, trying to build XJC with Java 11 leads to:

```
[ERROR] error: module not found: resolver
```

`mvn clean install` log:

[std.txt](https://github.com/eclipse-ee4j/jaxb-ri/files/2985294/std.txt)

**Comment by lukasj** [comment]
works fine on mac with:

```
lukas$ java -version
java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)
```

What do I have to do in order to reproduce the issue?

**Comment by highsource** [comment]
I'm sorry I don't know what do you have to do to reproduce this. Does not work for me with:
```
java version "11.0.1" 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)
```

**Comment by bravehorsie** [comment]
Please follow my comment in #1299 looks like a module path windows issue.
