### ISSUE TITLE
API Javadoc is not hosted on the project website

### ISSUE THREAD

**Issue by Vhati** [eclipse-ee4j/jaxb-ri#1308]
The guide has a broken link, pointing to API Javadocs that don't exist.

[Source](https://github.com/eclipse-ee4j/jaxb-ri/blob/afa88da958e1cfb953fb4c38f0b4a1cfec608162/jaxb-ri/docs/release-documentation/src/docbook/overview.xml#L88-L92): overview.xml
````
<listitem>
	<para><link
	xlink:href="api/">Javadoc
	API documentation (javax.xml.bind.*)</link></para>
</listitem>
````
Looks like the normal navigation is through...
* https://github.com/eclipse-ee4j/jaxb-ri
    * JAXB Users Guide
        *  Table of Contents
            * Overview / 1. Documentation
        * OR
        * Single HTML
* https://javaee.github.io/jaxb-v2/
    * User Guide
        * Overview / 1. Documentation
    * OR
    * JAXB Users Guide
        *  Table of Contents
            * Overview / 1. Documentation
        * OR
        * Single HTML

The "API documentation" links from all those routes dead end at:
https://javaee.github.io/jaxb-v2/doc/user-guide/api/
&nbsp;
&nbsp;
Besides generating the Javadocs, it'd be good to have a prominent link to them.

And a link to the guide's table of contents, rather than just a few individual chapters. That compounds the confusion between "User Guide" and "JAXB Users Guide".

In hindsight, I could have clicked readme.md's "Sample Apps" link and scrolled up (same chapter), but that's not obvious.

**Comment by bravehorsie** [comment]
Thanks for reporting, currently correct link to API is here: https://eclipse-ee4j.github.io/jaxb-ri/. I will fix the userguide links and update README.md to point to eclipse site docs. javaee.github.io is not supported any more.
