### ISSUE TITLE
Error When I run xjc command from windows terminal

### ISSUE THREAD

**Issue by r-leafar** [eclipse-ee4j/jaxb-ri#1323]
Error occurred during initialization of boot layer
java.lang.module.FindException: Module com.sun.tools.rngdatatype not found, requ
ired by com.sun.tools.xjc

Java version: Java 12.

When I run xjc from cmd.

**Comment by r-leafar** [comment]
After look on xjc.bat I did the following steps and Apparently Fix.

Step 1
I create a folder with name %JABX_HOME%/lib
Step 2
I copy from %JABX_HOME%/mod/relaxng-datatype.jar and paste %JABX_HOME%/lib/relaxng-datatype.jar
Step 3
I rename %JABX_HOME%/lib/relaxng-datatype.jar to %JABX_HOME%/lib/relaxngDatatype.jar
Step 4
Copy %JABX_HOME%/mod/javax.activation-api.jar with other name  %JABX_HOME%/mod/javax.activation.jar

thereafter it´s work. xD

I made the changes according to the paths specified in xjc.bat

**Comment by lukasj** [comment]
not an issue in 2.3.3-b02
