### ISSUE TITLE
release build manifest Class-Path incorrect.

### ISSUE THREAD

**Issue by gbburkhardt** [eclipse-ee4j/jaxb-ri#1335]
The Class-Path entries for some jar files in the 2.3.2 release include version numbers in jar file names.  The only problem is that those files don't exist in the mod directory included in "jaxb-ri-2.3.2.zip", so the Java compiler gives warnings about missing files.  For example, in jaxb-runtime.jar, the Class-Path is 
jakarta.xml.bind-api-2.3.2.jar txw2-2.3.2.jar istack-commons-runtime-3.0.8.jar stax-ex-1.8.1.jar FastInfoset-1.2.16.jar jakarta.activation-api-1.2.1.jar

So I would like to see the Class-Path entries be consistent with the files included in the release, or be removed.

**Comment by lukasj** [comment]
not an issue anymore in 2.3.3-b02
