### ISSUE TITLE
XSOM - Source version 6 is not allowed

### ISSUE THREAD

**Issue by GedMarc** [eclipse-ee4j/jaxb-ri#1342]
Hi All,

When building XSOM the following error is presented - 
```
Source option 6 is no longer supported. Use 7 or later.
[ERROR] Target option 6 is no longer supported. Use 7 or later.
```

Please consider dropping backwards support from JDK 8, The libraries are becoming a bit too far out of date with current JDK versions in the effort of trying to maintain backwards compatibility

**Comment by lukasj** [comment]
JDK 12/13 are not LTS version, so support for them is questionable at this point. The requirement now is to support 8 and 11. Documentation will be updated at some point as well.
