### ISSUE TITLE
XJC bindings files do not work for DTDs

### ISSUE THREAD

**Issue by joankaradimov** [eclipse-ee4j/jaxb-ri#1343]
I get this error when running XJC:
```
parsing a schema...
[ERROR] Unsupported binding namespace "http://java.sun.com/xml/ns/jaxb". Perhaps you meant "http://java.sun.com/xml/ns/jaxb/xjc"?
  line 7 of file://some/path

[ERROR] cvc-elt.1.a: Cannot find the declaration of element 'jxb:bindings'.
  line 7 of file://some/path
```

One of the (many) files I tested with looks something like this:
```xml
<jxb:bindings version="2.0"
              xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
              xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc"
              xmlns:xsd="http://www.w3.org/2001/XMLSchema"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://java.sun.com/xml/ns/jaxb http://java.sun.com/xml/ns/jaxb/bindingschema_2_0.xsd">

  <!-- some-stuff -->

</jxb:bindings>
```

Looking at the implementations of [ExtensionBindingChecker::startElement](https://github.com/eclipse-ee4j/jaxb-ri/blob/afa88da958e1cfb953fb4c38f0b4a1cfec608162/jaxb-ri/xjc/src/main/java/com/sun/tools/xjc/reader/ExtensionBindingChecker.java#L81) and [DTDExtensionBindingChecker::startElement](https://github.com/eclipse-ee4j/jaxb-ri/blob/afa88da958e1cfb953fb4c38f0b4a1cfec608162/jaxb-ri/xjc/src/main/java/com/sun/tools/xjc/reader/dtd/bindinfo/DTDExtensionBindingChecker.java#L57) I can see that the DTD implementation does nothing to consider `Const.JAXB_NSURI` a valid XML namespace attribute.

Environment:
Gradle 5.6.1 on Java 12.0.2 using the ant jaxb plugin. These are the Maven artifacts:

```
'javax.xml.bind:jaxb-api:2.3.1'
'com.sun.xml.bind:jaxb-core:2.3.0.1'
'com.sun.xml.bind:jaxb-xjc:2.3.2'
'com.sun.xml.bind:jaxb-impl:2.3.2'
```

**Comment by antoniosanct** [comment]
Hi, @joankaradimov 
Did you test again with 2.x or 4.x JAXB XJC version?
Regards,
Antonio.

**Comment by joankaradimov** [comment]
Sorry, no. I no longer work on that codebase.

@boris-petrov, do you have any input here?

**Comment by boris-petrov** [comment]
@antoniosanct I see the exact same errors as in the original post with JAXB XJC version 2.3.8.
