### ISSUE TITLE
Merging a fork into the codemodel

### ISSUE THREAD

**Issue by phax** [eclipse-ee4j/jaxb-ri#1353]
Hi guys,
long long time ago (September 2013), I created a fork of the old codemodel version. That fork is available at https://github.com/phax/jcodemodel/ and contains LOTS of extensions and new APIs.

I got the question at https://github.com/phax/jcodemodel/issues/73 if this can somehow be merged back into the main trunk.

Do you see a possibility to do that? If so, how to progress? Any input is appreciated.

Thanks, Philip

**Comment by lukasj** [comment]
First make sure you have read https://github.com/eclipse-ee4j/jaxb-ri/blob/master/CONTRIBUTING.md and signed [ECA](https://www.eclipse.org/legal/ECA.php).

Then just submit a PR and we'll follow up from there. If the change is going to be big, we probably have to take one additional step and that can take some time. Let's see...

**Comment by phax** [comment]
@lukasj as I don't have the resources to do it, I think you can close this issue for now. Thanks for keeping it open.

**Comment by lukasj** [comment]
ok, closing for now
