### ISSUE TITLE
javac: invalid target release: 9

### ISSUE THREAD

**Issue by 141801** [eclipse-ee4j/jaxb-ri#1365]
**env:**
/home/jaxb-ri/jaxb-ri# mvn -version
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_222, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.9.0-9-amd64", arch: "amd64", family: "unix"

**branch:**
  2.3.2-RI
**error log:**
[ERROR] javac: invalid target release: 9
Usage: javac <options> <source files>
use -help for a list of possible options
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JAXB BOM ........................................... SUCCESS [ 13.653 s]
[INFO] JAXB BOM with ALL dependencies ..................... SUCCESS [  0.020 s]
[INFO] JAXB Reference Implementation ...................... SUCCESS [ 53.258 s]
[INFO] JAXB TXW parent .................................... SUCCESS [  0.038 s]
[INFO] TXW2 Runtime ....................................... FAILURE [  4.601 s]
[INFO] TXW2 Compiler ...................................... SKIPPED
[INFO] JAXB Runtime parent ................................ SKIPPED
[INFO] JAXB Runtime ....................................... SKIPPED
[INFO] JAXB XJC ........................................... SKIPPED
[INFO] JAXB JXC ........................................... SKIPPED
[INFO] Parent for osgi testing modules. ................... SKIPPED
[INFO] osgi-test-parent ................................... SKIPPED
[INFO] osgi-test-runtime .................................. SKIPPED
[INFO] JAXB bundles ....................................... SKIPPED
[INFO] Old JAXB Runtime ................................... SKIPPED
[INFO] osgi-test-xjc ...................................... SKIPPED
[INFO] Old JAXB XJC ....................................... SKIPPED
[INFO] osgi-test-jxc ...................................... SKIPPED
[INFO] Old JAXB JXC ....................................... SKIPPED
[INFO] JAXB Documentation parent .......................... SKIPPED
[INFO] JAXB Release Documentation ......................... SKIPPED
[INFO] JAXB samples ....................................... SKIPPED
[INFO] JAXB RI ............................................ SKIPPED
[INFO] JAXB OSGI parent ................................... SKIPPED
[INFO] JAXB OSGI .......................................... SKIPPED
[INFO] osgi-test-osgi ..................................... SKIPPED
[INFO] JAXB OSGi Tests .................................... SKIPPED
[INFO] JAXB WWW Help files ................................ SKIPPED
[INFO] osgi-test-core ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:15 min
[INFO] Finished at: 2019-10-16T09:29:19+00:00
[INFO] Final Memory: 24M/58M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on pr
oject txw2: Compilation failure
[ERROR] javac: invalid target release: 9
[ERROR] Usage: javac <options> <source files>
[ERROR] use -help for a list of possible options
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :txw2

**Comment by 141801** [comment]
root@instance-12:/home/jaxb-ri/jaxb-ri# java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1~deb9u1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

**Comment by lukasj** [comment]
Build requires jdk 11 and preferred maven is 3.6.0

**Comment by 141801** [comment]
Thanks for your kindness help .
