### ISSUE TITLE
Inconsistency of provided services between classpath and modulepath

### ISSUE THREAD

**Issue by mipastgt** [eclipse-ee4j/jaxb-ri#1368]
The file
jaxb-ri/runtime/impl/src/main/resources/META-INF/services/javax.xml.bind.JAXBContext
says that this jar provides a service javax.xml.bind.JAXBContext with the implementation
com.sun.xml.bind.v2.ContextFactory
This looks inconsistent with the content of the file
jaxb-ri/runtime/impl/src/main/java/module-info.java
which provides javax.xml.bind.JAXBContextFactory with com.sun.xml.bind.v2.JAXBContextFactory
Shouldn't these two locations contain the same content?

**Comment by lukasj** [comment]
not necessarily - there is no requirement on the provider for the factory to implement JAXBContextFactory. But I agree it's better to be consistent here.

**Comment by mipastgt** [comment]
The current situation means that some modular library code will just stop working if a user dares to put it on the classpath instead of the module path, which he should be able to do. This can also happen accidentally in test code if you look at the magic that, e.g., Maven does to get tests working in a modular setup.

**Comment by lukasj** [comment]
thanks for catching this! I apparently run wrong set of tests on my end :-/ Should be OK now

**Comment by mipastgt** [comment]
Yes, looks ok now. But you might consider adding the old service to the module-info.java too in order to make the transition from non-modular to modular java easier. But that is a political decision whether you want to actually remove the old service here or not.

**Comment by mipastgt** [comment]
The longer I think about this the more I come to the conclusion that the declarations in module-info.java and META-INF/services should ALWAYS be identical. If you actually want to remove some deprecated API then you should also do it consistently in both places and don't create any confusion between modular and non-modular behaviour.
