### ISSUE TITLE
Wrong use of "module com.sun.tools.jxc" in /bin/*.sh|bat

### ISSUE THREAD

**Issue by mu-so** [eclipse-ee4j/jaxb-ri#1369]
Hey,

compiled master branch on my maschine to run xjc with openjdk 11. Just saw in the bin/*.sh|bat files, that `com.sun.tools.jxc` ist used. As I saw, the module name changed to
   `org.glassfish.jaxb.jxc` and    `org.glassfish.jaxb.xjc`

Keep up the good work, see attached git diff with fixed module name.

Greetings,
Mustafa
[patch.txt](https://github.com/eclipse-ee4j/jaxb-ri/files/3880244/patch.txt)

**Comment by lukasj** [comment]
the thing here is  that module names in scripts are correct. What is wrong is the content of the zip distribution which should contain just bundle jars ("old" com.sun. artifacts). and dependencies and not all smaller module artifacts (such as istack, txw2 etc).

**Comment by mu-so** [comment]
See https://github.com/eclipse-ee4j/jaxb-ri/blob/master/jaxb-ri/xjc/src/main/java/module-info.java
The module name is `org.glassfish.jaxb.xjc`

**Comment by lukasj** [comment]
what is supposed to be in the binary distribution is https://github.com/eclipse-ee4j/jaxb-ri/blob/master/jaxb-ri/bundles/xjc/src/main/java/module-info.java instead, that is artifact with `com.sun.tools.xjc` module name.

The difference between these two artifacts is that `com.sun.tools.xjc` = `com.sun.codemodel` + `com.sun.xml.dtdparser` + `com.sun.tools.rngdatatype` + `com.sun.tools.rngom` + `com.sun.xml.xsom` + `com.sun.istack.tools` + `org.glassfish.jaxb.xjc`. I do not think consumers of JAXB should care about these, quite low-level, libraries, all they want is just xjc.

**Comment by mu-so** [comment]
Thanks for explaining. I get the problem, so the assembly missing the "wrapper" module here:
https://github.com/eclipse-ee4j/jaxb-ri/blob/master/jaxb-ri/bundles/ri/src/main/assembly/assembly.xml
after line 80 something like
 <include>com.sun.xml.bind:jaxb-xjc</include>
I will close this issue and delete my pull request
KR
M
