### ISSUE TITLE
Maven Central has bad meta data

### ISSUE THREAD

**Issue by llsouder** [eclipse-ee4j/jaxb-ri#1419]
All of our maven builds using 2.3.1 are broken.
Looks like someone pushed bad meta data to maven central.
https://repo1.maven.org/maven2/org/glassfish/jaxb/jaxb-runtime/maven-metadata.xml

It only includes the 3.0.0-M version.

**Comment by lukasj** [comment]
thanks for heads up, I filed: https://issues.sonatype.org/browse/MVNCENTRAL-5695

**Comment by llsouder** [comment]
thank you.  

I cannot view that issue.  Hopefully it is the permissions.
```
You can't view this issue
It may have been deleted or you don't have permission to view it.
```

**Comment by lukasj** [comment]
Don't know why they are imposing security restrictions on this kind of issues but the most important thing is that they are working on it

**Comment by lukasj** [comment]
Refreshed metadata are heading to central, they should be there within an hour. Feel free to reopen this if this issues persists tomorrow (or anytime later). Thanks!
