### ISSUE TITLE
JAXB RI 3.0.0 RC1 validation with nist schema xsd having "<annotation><documentation>" elements fails

### ISSUE THREAD

**Issue by gurunrao** [eclipse-ee4j/jaxb-ri#1422]
JAXB RI 3.0.0 RC1 validation with nist schema for xsd having annotation,documentation elements fails with following error:
java.lang.Exception: The xjc invoker Driver.run( -d, /schema2java/nisttest/float/classes/float/enumeration/enumeration2, -p, javasoft.sqe.tests._float.enumeration.enumeration_2, /tests/schema2java/nisttest/float/enumeration/enumeration-2.xsd ) failed
with the message "jakarta.xml.bind.JAXBException
- with linked exception:
[com.sun.xml.internal.bind.v2.runtime.IllegalAnnotationsException: 1 counts of IllegalAnnotationExceptions
com.sun.xml.bind.api.impl.NameConverter is an interface, and JAXB can't handle interfaces.
	this problem is related to the following location:
		at com.sun.xml.bind.api.impl.NameConverter
		at public com.sun.xml.bind.api.impl.NameConverter com.sun.tools.xjc.reader.xmlschema.bindinfo.BIGlobalBinding.nameConverter
		at com.sun.tools.xjc.reader.xmlschema.bindinfo.BIGlobalBinding
]"
	at com.sun.jaxb_tck.lib.SchemaCompiler._xjc(SchemaCompiler.java:77)
	at com.sun.jaxb_tck.lib.SchemaCompiler.access$000(SchemaCompiler.java:30)
	at com.sun.jaxb_tck.lib.SchemaCompiler$1.run(SchemaCompiler.java:53)

**Comment by lukasj** [comment]
> with the message "jakarta.xml.bind.JAXBException

2.3.2 is not going to work with renamed APIs

**Comment by lukasj** [comment]
problem is in the `jakarta.xml.bind` API which tries to load internal implementation of JAXB from Java SE 8 (can be seen from com.sun.xml.**internal**.bind.v2.runtime.IllegalAnnotationsException) which is no longer valid implementation
