### ISSUE TITLE
XJC -relaxng still supported ?

### ISSUE THREAD

**Issue by tvallin** [eclipse-ee4j/jaxb-ri#1450]
Documentation says : "-relaxng  : treat input as RELAX NG(experimental,**unsupported**)" 

But there is relaxng sample available in current jaxb, and not working. Few classes are related to relaxng in xjc folder.

Is relaxng going to be removed from the project or supported in the future ?

**Comment by rkottmann** [comment]
I have the same question

**Comment by lukasj** [comment]
the relaxng supported has been resurrected (to the certain extent)
