### ISSUE TITLE
GlassFish needs an M4 release 

### ISSUE THREAD

**Issue by smillidge** [eclipse-ee4j/jaxb-ri#1455]
GlassFish needs an M4 release that incorporates https://github.com/eclipse-ee4j/jaxb-ri/pull/1448 for a June milestone release.

**Comment by lukasj** [comment]
you should be able to use 3.0.0-SNAPSHOT in ~30minutes...

**Comment by smillidge** [comment]
I tried the snapshot and it fixes the GlassFish issue. Can you do a milestone. Once we have that GlassFish starts well and the admin console deploys and is accessible

**Comment by smillidge** [comment]
@lukasj any chance you can push a M4 release ASAP as this is the final dependencie required for an M1 release of GlassFish 6.

**Comment by arjantijms** [comment]
@lukasj If you don't have time, I think I can do an M4 release as well. They won't go to Maven central, only to staging, and can be removed when needed.

**Comment by lukasj** [comment]
I really don't need 4 emails on the same topic ;-)

**Comment by smillidge** [comment]
We're just excited to be this close!

Thanks for your help.

**Comment by lukasj** [comment]
I was only hoping to get a chance to fix (at least some) QLs for GF M1...
