### ISSUE TITLE
XJC-generated JavaDoc is unreadable in IDE

### ISSUE THREAD

**Issue by osobolev** [eclipse-ee4j/jaxb-ri#1471]
HTML tags in the generated JavaDoc are escaped, for example `&lt;p&gt;` is being output instead of `<p>`. Though javadoc tool produces correct HTML, other tools like IDEs do not process escaped tags. This escaping behaviour was introduced in 2.3.3 and seems unnecessary.

**Comment by gitmotte** [comment]
see #1357 - changed with comment "fixed javadoc generation in codemodel to escape special characters"

**Comment by lukasj** [comment]
@gitmotte why do you think that change has something to do with this?

**Comment by gitmotte** [comment]
you only have to look into the commit history or the commits of the pull request: #1357 

https://github.com/eclipse-ee4j/jaxb-ri/pull/1357/commits/8e7ba03c72b4c0e6d45780598554760431ec9bc7#diff-9f7671506038fb663c705875324224c8b9743440c78fb65580ce48f12e3b4ae1

**Comment by lukasj** [comment]
that code does not handle javadoc generation, so the question remain - why do you think that change has something to do with javadoc generation?

**Comment by gitmotte** [comment]
JDocComment extends JCommentPart - a JDocComment will be created when calling JDefinedClass#javadoc()

Here is a screenshot during a **debugging session during java code generation**:

![codemodel_debug_javadoc](https://user-images.githubusercontent.com/28668096/97779668-da2b4f00-1b7f-11eb-969a-c6dc8a163754.jpg)

As far as i know some html-tags are allowed within javadoc. The generation of none-escaped javadoc-comments without using any special doclint-flags works quiet well with adoptopenjdk-14 and maven 3.6.3

![generated-javadoc-from-not-escaped](https://user-images.githubusercontent.com/28668096/97779708-25456200-1b80-11eb-85c5-c9c054fd4110.jpg)

**Comment by gitmotte** [comment]
For allowed HTML-Tags within javadoc comments have a look at com.sun.tools.doclint.HtmlTag

**Comment by lukasj** [comment]
OK, you know for which schema/source generation is not as you expect. You know how exactly you can reproduce the issue you are seeing. Why you cannot just describe/attach the source and steps required to reproduce the behaviour and expect someone else to spend his time guessing what you are doing? For instance my Ide fails to parse a source file - based on this, can you say about which IDE and about which file I'm talking about???

> The generation of none-escaped javadoc-comments without using any special doclint-flags works quiet well with adoptopenjdk-14 and maven 3.6.3

has not been always true, see ie #1023. Just try to generate some code by XJC from JDK 7 or older and run javadoc from JDK 8+ on such sources

> I would prefer that the user of codemodel is responsible to encode javadoc correctly without any auto-enodings !

this is mostly done by [JavadocEscapeWriter](https://github.com/eclipse-ee4j/jaxb-ri/blob/master/jaxb-ri/codemodel/codemodel/src/main/java/com/sun/codemodel/util/JavadocEscapeWriter.java#L43) which is called by XJC and this issue is about XJC.

I can only guess that what you are talking about is in core codemodel, which means that you are describing different problem even though the cause might be the same - can you point me to specific part in your description where I was supposed to be able to spot the difference?

**Comment by gitmotte** [comment]
in this case i don't use xjc. i'm using codemodel (which is part of jaxb-ri and seems to be used by xjc too) to generate java-code for my personal needs, therefore i can't share the code ;)

the result in my case is the same as described by @osobolev
```

**Comment by lukasj** [comment]
Is it that hard to attach a reproducer based on the code you use, not necessarily exactly same one? Without that I'm not willing to spend time on this. Maybe some other committer is. Sorry.

**Comment by gitmotte** [comment]
Yes, i'd spend you a reproducer - just give me some time ...

**Comment by gitmotte** [comment]
see https://github.com/gitmotte/codemodel_issue_1471

**Comment by gitmotte** [comment]
@lukasj  #1480 came in with the same change.

Can you now identify the problem with the provided testcase?

if xjc uses JavadocEscapeWriter.java to render javadoc comments, why did you modify JCommentPart.java?

**Comment by lukasj** [comment]
@gitmotte I don't know. You're expecting immediate answer during the weekend?

**Comment by gitmotte** [comment]
no, but I had time to write today.
why so offensive? nobody forces you to read emails on the weekend.

**Comment by lukasj** [comment]
> why so offensive?

I was just asking since I do find using exclamation marks (as you did) offensive and impolite as I do find pinging people if one does not get answer within 24 hours

**Comment by gitmotte** [comment]
i think that my way of writing is very common. exclamation marks are part of the language to emphasize something and pinging people is to address someone directly. but if it bothers you, i will avoid it now.

**Comment by lukasj** [comment]
#1358 is related as to why the original change - using '@' and '&' in (javadoc) comments forced almost every user to use doclint:none

Upper-case letter are part of the language too and only very limited set of people is using it.

**Comment by gitmotte** [comment]
> #1358 is related as to why the original change - using '@' and '&' in (javadoc) comments forced almost every user to use doclint:none

this sounds reasonable at first sight @ and & to encode, but what happens if someone has already encoded himself ? an &amp; becomes &&amp; ...

furthermore all occurrences of < and > will now be encoded, which is not always correct. 

> Upper-case letter are part of the language too and only very limited set of people is using it.

but it is not usual to use upper-case letters in normal sentences. apart from that i had used an exclamation mark once. this is anything but impolite.

**Comment by gitmotte** [comment]
Thanks for this fix

**Comment by mauromol** [comment]
Hello,
which version of JAXB is supposed to contain the fix?
I don't know if it's the same problem, but with JAXB 2.3.3 the generated Javadoc for type classes contain escaped `<p>`, `<pre>` etc. tags, so rendering of the Javadoc in Eclipse IDE is completely broken. Here is an example when I generate code for the SAML 2.0 metadata schema (https://docs.oasis-open.org/security/saml/v2.0/saml-schema-metadata-2.0.xsd) for the generated `EntitiesDescriptorType` type using JAXB XJC 2.3.3:

```java
/**
 * &lt;p&gt;Classe Java per EntitiesDescriptorType complex type.
 * 
 * &lt;p&gt;Il seguente frammento di schema specifica il contenuto previsto contenuto in questa classe.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="EntitiesDescriptorType"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature" minOccurs="0"/&amp;gt;
 *         &amp;lt;element ref="{urn:oasis:names:tc:SAML:2.0:metadata}Extensions" minOccurs="0"/&amp;gt;
 *         &amp;lt;choice maxOccurs="unbounded"&amp;gt;
 *           &amp;lt;element ref="{urn:oasis:names:tc:SAML:2.0:metadata}EntityDescriptor"/&amp;gt;
 *           &amp;lt;element ref="{urn:oasis:names:tc:SAML:2.0:metadata}EntitiesDescriptor"/&amp;gt;
 *         &amp;lt;/choice&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *       &amp;lt;attribute name="validUntil" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&amp;gt;
 *       &amp;lt;attribute name="cacheDuration" type="{http://www.w3.org/2001/XMLSchema}duration" /&amp;gt;
 *       &amp;lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}ID" /&amp;gt;
 *       &amp;lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EntitiesDescriptorType", propOrder = {
    "signature",
    "extensions",
    "entityDescriptorOrEntitiesDescriptor"
})
public class EntitiesDescriptorType {
}
```

This did not happen with JAXB 2.2.11, here is another example generated with JAXB XJC 2.2.11 for a different schema, where escaping is correct and is only applied on `<` and `>` characters used to produce XML tags inside the `<pre>` block:

```java
/**
 * <p>Classe Java per FatturaElettronicaType complex type.
 * 
 * <p>Il seguente frammento di schema specifica il contenuto previsto contenuto in questa classe.
 * 
 * <pre>
 * &lt;complexType name="FatturaElettronicaType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FatturaElettronicaHeader" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2}FatturaElettronicaHeaderType"/&gt;
 *         &lt;element name="FatturaElettronicaBody" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2}FatturaElettronicaBodyType" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="versione" use="required" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2}FormatoTrasmissioneType" /&gt;
 *       &lt;attribute name="SistemaEmittente" type="{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2}String10Type" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FatturaElettronicaType", propOrder = {
    "fatturaElettronicaHeader",
    "fatturaElettronicaBody",
    "signature"
})
public class FatturaElettronicaType {
}
```

**Comment by osobolev** [comment]
Seems like it is fixed in 3.x, but it comes with change to jakarta.* namespace.

**Comment by lukasj** [comment]
has been backported through #1512

**Comment by mauromol** [comment]
> has been backported through #1512

So for the upcoming JAXB 2.3.4, if I understand it correctly. Thank you @lukasj! (and @osobolev as well)
