### ISSUE TITLE
Jakarta 3.0.0 illegal reflective access

### ISSUE THREAD

**Issue by ruckc** [eclipse-ee4j/jaxb-ri#1501]
Getting this from a shaded jar with jaxb-runtime 3.0.0

WARNING: Illegal reflective access by org.glassfish.jaxb.runtime.v2.runtime.reflect.opt.Injector to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)

**Comment by sify21** [comment]
It's said to be fixed two years ago https://github.com/eclipse-ee4j/jaxb-ri/issues/1197, so the code is reverted back?

**Comment by sify21** [comment]
adding `-Dorg.glassfish.jaxb.runtime.v2.bytecode.ClassTailor.noOptimize=true` removes the warning. I searched the codebase and found this line https://github.com/eclipse-ee4j/jaxb-ri/blob/d0386f88a6f53972614dbb4a9953c164d8f4dc79/jaxb-ri/runtime/impl/src/main/java/org/glassfish/jaxb/runtime/v2/runtime/reflect/opt/AccessorInjector.java#L28

**Comment by lukasj** [comment]
If one gets this on JDK 9+ then the cause of the problem is likely in the class loader of JAXB classes which is not able to read multi-release jar files. Such class loader is out of JAXB control.

Feel free to reopen if you can reproduce this with `-Djdk.util.jar.enableMultiRelease=force` providing details about JDK, environment and simple test case.

**Comment by sify21** [comment]
Thanks for the info, in my case I'm building a fat-jar, and I forget to add `Multi-Release: true` to the manifest. After adding this, I don't need the `noOptimize` thing.

**Comment by bourgesl** [comment]
To make JAXB RI 2.3.3 work with JDK16, it is mandatory to set the system property 'org.glassfish.jaxb.runtime.v2.bytecode.ClassTailor.noOptimize=true'

See my comments: 
https://github.com/eclipse-ee4j/jaxb-ri/issues/1197#issuecomment-810908755

Is it true with JAXB RI 3.0 ?

**Comment by lukasj** [comment]
@bourgesl as long as the environment understands multi-release jar files and can work with them properly, no option is needed. If one needs to use some custom classloaders for some reason, he needs to deal with possibly multi-release input at that level himself

**Comment by mkarg** [comment]
I had the same problem and confirm that `Multi-Release: true` in the shaded JAR's manifest solved it, even on JDK16!
