### ISSUE TITLE
jaxb-osgi v2.3.3: ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory: missing Capability

### ISSUE THREAD

**Issue by puce77** [eclipse-ee4j/jaxb-ri#1507]
When using the jaxb-osgi module v2.3.3 in a Java 11 based OSGi environment, I get the following exception:

```
SCHWERWIEGEND: Implementation of JAXB-API has not been found on module path or classpath.  
javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception: 
[java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory]
```
Since the ContextFactory is loaded by the ServiceLoader, I guess I need something like:
```
Require-Capability: osgi.extender;filter:="(&(osgi.extender=osgi.co
 mponent)(version>=1.4.0)(!(version>=2.0.0)))",osgi.extender;filter:="(o
 sgi.extender=osgi.serviceloader.processor)",osgi.serviceloader;filter:=
 "(osgi.serviceloader=javax.xml.bind.JAXBContextFactory)";cardinality:=m
 ultiple,osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=11))"
```
But this didn't work either.

If I understood the following article correctly: https://blog.osgi.org/2013/02/javautilserviceloader-in-osgi.html
then something like the following is missing in the Manifest of jaxb-osgi for each of its registered services:

```
 Require-Capability: osgi.extender;
    filter:="(osgi.extender=osgi.serviceloader.registrar)"
  Provide-Capability: osgi.serviceloader;
    osgi.serviceloader=foo.bar.MySPI
```

**Comment by puce77** [comment]
I asked a related question on StackOverflow: https://stackoverflow.com/questions/65868619/jaxb-osgi-with-java-11

**Comment by puce77** [comment]
The following patch: https://github.com/eclipse-ee4j/jaxb-ri/compare/2.3.3-RI...puce77:1507-jaxb-osgi-serviceloader?expand=1

generates the following Manifest attributes:

`Provide-Capability: osgi.serviceloader;osgi.serviceloader="javax.xml.bin
 d.JAXBContextFactory",osgi.serviceloader;osgi.serviceloader="com.sun.to
 ols.xjc.Plugin"`
`Require-Capability: osgi.extender;filter:="(osgi.extender=osgi.servicelo
 ader.registrar)",osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"`

I have to check if they are correct (how excatly are multiple service loader interfaces registered?) and check if this solves the loading issue.

**Comment by lukasj** [comment]
dependency on osgi extender is not required as long as there is `org.glassfish.hk2.osgiresourcelocator` available, only make sure that it is started before jaxb-api/osgi; see also https://github.com/eclipse-ee4j/saaj-api/issues/43

**Comment by puce77** [comment]
With this patch Apache Aries SPI Fly Dynamic Weaving Bundle (1.3.2) is able to find the service registrations:
```
2021-02-13 12:09:31 INFO org.apache.aries.spifly.BaseActivator log - Registered provider com.sun.xml.bind.v2.JAXBContextFactory of service javax.xml.bind.JAXBContextFactory in bundle com.sun.xml.bind.jaxb-osgi
2021-02-13 12:09:31 INFO org.apache.aries.spifly.BaseActivator log - Registered provider com.sun.tools.xjc.addon.code_injector.PluginImpl of service com.sun.tools.xjc.Plugin in bundle com.sun.xml.bind.jaxb-osgi
2021-02-13 12:09:31 INFO org.apache.aries.spifly.BaseActivator log - Registered provider com.sun.tools.xjc.addon.locator.SourceLocationAddOn of service com.sun.tools.xjc.Plugin in bundle com.sun.xml.bind.jaxb-osgi
2021-02-13 12:09:31 INFO org.apache.aries.spifly.BaseActivator log - Registered provider com.sun.tools.xjc.addon.sync.SynchronizedMethodAddOn of service com.sun.tools.xjc.Plugin in bundle com.sun.xml.bind.jaxb-osgi
2021-02-13 12:09:31 INFO org.apache.aries.spifly.BaseActivator log - Registered provider com.sun.tools.xjc.addon.at_generated.PluginImpl of service com.sun.tools.xjc.Plugin in bundle com.sun.xml.bind.jaxb-osgi
2021-02-13 12:09:31 INFO org.apache.aries.spifly.BaseActivator log - Registered provider com.sun.tools.xjc.addon.episode.PluginImpl of service com.sun.tools.xjc.Plugin in bundle com.sun.xml.bind.jaxb-osgi
2021-02-13 12:09:31 INFO org.apache.aries.spifly.BaseActivator log - Registered provider com.sun.tools.xjc.addon.accessors.PluginImpl of service com.sun.tools.xjc.Plugin in bundle com.sun.xml.bind.jaxb-osgi
```
But I still get the error:
```
javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory not found by 
```

**Comment by puce77** [comment]
@lukasj Thanks for the hint. I've seen now that there is even [some special code in jaxb-api](https://github.com/eclipse-ee4j/jaxb-api/blob/2.3.3/jaxb-api/src/main/java/javax/xml/bind/ServiceLoaderUtil.java) (not jaxb-ri) for `org.glassfish.hk2.osgiresourcelocator.ServiceLoader`!??

And why is the classloader passed to ContextFinder not also passed to `java.util.ServiceLoader` in ServiceLoaderUtil?

I will try now `org.glassfish.hk2.osgiresourcelocator`as you suggested even though the issue https://github.com/eclipse-ee4j/saaj-api/issues/43 mentions this is likely not the best approach in long term.

**Comment by lukasj** [comment]
It's the api who is responsible for finding appropriate implementation(s). If the implementation is not found, the possible cause may be also wrong API being used by the user. There is a big difference between using `JAXBContext.newInstance(...)` methods without `ClassLoader` argument and with it - in the OSGi env, the latter is typically the one to be used. Another possible cause, if you want to go the Aries way is that the API jar itself is missing sth like:
```Require-Capability: osgi.serviceloader; filter:="(osgi.serviceloader=javax.xml.bind.JAXBContextFactory)";cardinality:=multiple,osgi.extender; filter:="(osgi.extender=osgi.serviceloader.processor)"```

> And why is the classloader passed to ContextFinder not also passed to java.util.ServiceLoader in ServiceLoaderUtil?

Any reason why it should be? Do you have a reproducible case where current behaviour is failing with `org.glassfish.hk2.osgiresourcelocator`and `JAXBContext.newInstance` method taking `ClassLoader` argument is used?
