### ISSUE TITLE
Iterator of CClassInfo.listSubclasses depends on state of object

### ISSUE THREAD

**Issue by ehambuch** [eclipse-ee4j/jaxb-ri#1516]
I am chasing a bug in the generation process of jxc and stepped over a bug in **CClassInfo** of jaxb-xjc:

``
    public Iterator<CClassInfo> listSubclasses() {
        return new Iterator<CClassInfo>() {
            CClassInfo cur = firstSubclass;
            public boolean hasNext() {
                return cur!=null;
            }

            public CClassInfo next() {
                CClassInfo r = cur;
                cur = cur.nextSibling;
                return r;
            }
...
        };
    }
``
The reference to **nextSibling** is defined in the outer class **CClassInfo** but should be a state of the **Iterator**. If listSubclasses() is called twice, the state of the Iterator is not reset to the start.
Proposal: replace firstSubclass by a real java.util.Collection and return a clean Iterator from the Collection then.

**Comment by lukasj** [comment]
do you have some test case for this?

**Comment by ehambuch** [comment]
No, sorry. My fault, it's not a bug.
