### ISSUE TITLE
Updating JAXB to 3.0.2 from 2.3.6 causes `javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found`

### ISSUE THREAD

**Issue by Ahmad-alsanie** [eclipse-ee4j/jaxb-ri#1607]
Updating to latest JAXB breaks our spingboot app, we have the following in place:
```
 <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-impl</artifactId>
        </dependency>
```
Any ideas ?

**Comment by lukasj** [comment]
`javax.xml.bind:jaxb-api` became `jakarta.xml.bind:jakarta.xml.bind-api`, see https://wiki.eclipse.org/Jakarta_EE_Maven_Coordinates

**Comment by Ahmad-alsanie** [comment]
Thanks @lukasj I've updated my app with the new dependency but still getting the same exception. I'll try to check the dependency tree and effective pom, will see if something weird is going on underneath and update here, let me know if you've other suggestions as well. Appreciate your help!

**Comment by Ahmad-alsanie** [comment]
I had a dependency that was pulling `javax.xml.bind:jaxb-api`. Tried to exclude that as well as updating it but faced the following:
```
Cause: java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlElement
```
Looking further into this made me realize that I needed to add:
```
<dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
        </dependency>
```
but that didn't fix the issue still.
@lukasj Would this update require all `javax` artifacts to be updated to `jakarta` ? As I have dependencies on:
```
javax.servlet.jsp
jstl
javax.servlet.jsp-api
```
etc...

This would be a huge burden for our consumers and it would require lots of updates...

**Comment by lukasj** [comment]
> Would this update require all javax artifacts to be updated to jakarta ?

most likely yes

step 1) move to Jakarta EE 8 (same as Java EE 8 with different maven coordinates)
step 2) move to Jakarta EE 9+ - this is going to bring `jakarta` package namespace

wrt to spring, see also https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6
