### ISSUE TITLE
Support setting unmarshaller listener on binder

### ISSUE THREAD

**Issue by plutext** [eclipse-ee4j/jaxb-ri#1631]
abstract class Binder<XmlNode> supports setEventHandler but not setListener

So currently, it is necessary to do something like:

```
	public void setListener(Binder binder, Listener listener) throws IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException {
		
		org.glassfish.jaxb.runtime.v2.runtime.BinderImpl binderImpl = (org.glassfish.jaxb.runtime.v2.runtime.BinderImpl )binder;
		
		Method method = binderImpl.getClass().getDeclaredMethod("getUnmarshaller");
		method.setAccessible(true);
		Unmarshaller u  = (Unmarshaller)method.invoke(binderImpl);	
		u.setListener(listener);
	}
```

Please add setListener to Binder<XmlNode>

**Comment by lukasj** [comment]
filed https://github.com/eclipse-ee4j/jaxb-api/issues/228 to get this supported through API; meanwhile it is going to be supported by this implementation; in the other words - one can avoid reflection..
