### ISSUE TITLE
xjc uri  is still "http://java.sun.com/xml/ns/jaxb/xjc"

### ISSUE THREAD

**Issue by jimma** [eclipse-ee4j/jaxb-ri#1646]
The xjc uri is still java.sun.com one : https://github.com/eclipse-ee4j/jaxb-ri/blob/master/jaxb-ri/xjc/src/main/java/com/sun/tools/xjc/reader/Const.java#L31, should this be changed to "https://jakarta.ee/xml/ns/jaxb/xjc" ?

**Comment by lukasj** [comment]
jakarta.ee is reserved for the Jakarta specs; xjc uri is vendor extension and has nothing to do with the spec
