### ISSUE TITLE
com.sun.tools.xjc should run on JRE

### ISSUE THREAD

**Issue by VirtualTim** [eclipse-ee4j/jaxb-ri#1674]
When running a project depending on
```xml
<dependency>
	<groupId>com.sun.xml.bind</groupId>
	<artifactId>jaxb-xjc</artifactId>
	<version>4.0.1</version>
</dependency>
```
using a JRE (not JDK) I get the following error on startup:
```
Error occurred during initialization of boot layer
java.lang.module.FindException: Module jdk.compiler not found, required by com.sun.tools.xjc
```

Is jaxb-xjc expected to be able to work with a JRE, or does it only support JDK's?

**Comment by lukasj** [comment]
there is no reason for XJC to require JDK, JRE should be enough. It is JXC tool who requires JDK
