### ISSUE TITLE
Windows file path in systemId is fail

### ISSUE THREAD

**Issue by slavonnet** [eclipse-ee4j/jaxb-ri#1675]
https://github.com/eclipse-ee4j/jaxb-ri/blob/bc65602aeade58b344d6ddbefa534b06fdacffe6/jaxb-ri/xjc/src/main/java/com/sun/tools/xjc/reader/internalizer/DOMForest.java#L150

```systemId = file:/C:/Users/slavon/IdeaProjects/tacsonopypar/src/main/schema/final_5_2/www.xbrl.org/2003/xbrl-linkbase-2003-12-31.xsd```
```systemId.substring(5)``` is "/C:/..."

**Comment by lukasj** [comment]
`file:///C:/...` is valid on nix systems. Feel free to reopen with a sample which actually fails for some reason. Thanks.
