### ISSUE TITLE
Non-deterministic definition of default namespace @XmlSchema(namespace=...) in package-info.java

### ISSUE THREAD

**Issue by dmak** [eclipse-ee4j/jaxb-ri#1682]
Dear community,

I observe the following behavior on [XJC v4.0.1](https://central.sonatype.dev/artifact/org.glassfish.jaxb/jaxb-jxc/4.0.1):

The value of `namespace` member of `@XmlSchema` is not defined in deterministic  way, i.e. it changes from run to run. In particular when model for [this XSD](https://github.com/dmak/jaxb-xew-plugin/blob/946bb3bc92/src/test/resources/com/sun/tools/xjc/addon/xew/different-namespaces.xsd) is generated, it results either this `package-info.java`:
```
@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://example.com/entry", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package different_namespaces;
```
or this:
```
@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://example.com/namespaces", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package different_namespaces;
```
In case if sources are regenerated from time to time and committed to source repository, it results excessive differences.

**Comment by danshome** [comment]
@lukasj After we upgraded from JAXB-RI 4.0.2 to 4.03 we started getting form=qualified added to all our xsd elements that are generated using the com.sun.xml.ws:jaxws-maven-plugin. We don't find anything in the JAXB-RI release notes that seem related, but we stumbled on this change and It seems like it could be related.   Do you know if a way to stop that from happening?

**Comment by lukasj** [comment]
that regression is now fixed
