### ISSUE TITLE
DatatypeConverter.parseBoolean converts invalid strings to true

### ISSUE THREAD

**Issue by johannesherr** [eclipse-ee4j/jaxb-ri#1695]
The method `parseBoolean` in `javax.xml.bind.DatatypeConverterImpl` is supposed to convert only the values `"true"` and `"1"` to `true` (while ignoring leading and trailing whitespace). It, however, converts all strings to `true` that start with `"tru"` and are 4-5 characters long. For example:

```
DatatypeConverter.parseBoolean("trux"); // -> true
DatatypeConverter.parseBoolean("truu"); // -> true
DatatypeConverter.parseBoolean("truxx"); // -> true
DatatypeConverter.parseBoolean("truuu"); // -> true
```

This is caused by these segments in `parseBoolean`:
```
case 't':
    String strTrue = "rue";
    do {
        ch = literal.charAt(i++);
    } while ((strTrue.charAt(strIndex++) == ch) && i < len && strIndex < 3);

    if (strIndex == 3) {
        value = true;
    } else {
        return false;
    }
```
and:
```
if (i < len) {
    do {
        ch = literal.charAt(i++);
    } while (WhiteSpaceProcessor.isWhiteSpace(ch) && i < len);
}

if (i == len) {
    return value;
} else {
    return null;
}
```

In the first snippet `value` is assigned `true` also when the loop was left after comparing the third character, because the expression `strTrue.charAt(strIndex++) == ch` was false (that is when there is as mismatch between 'e' and the current character). strIndex will still be 3 (because it is incremented unconditionally).

That explains why `"trux"` is converter to `true`. The second snippet explains why the additional character in `"truxx"` is also ignored. If we haven't read the input completely the second input checks if there is whitespace to ignore. However it also uses an unconditional increment of the reading position, which causes the code to skip over the offending last character. Therefore `i == len` holds and the previously assigned `true` is returned.

**Comment by antoniosanct** [comment]
Hi, @johannesherr:
According to DatatypeConverterImpl javadoc, this class is deprecated and it would remove at any moment. In fact, the same comment recommends the use of jakartaee/jaxb-api version. Please, open an issue in this project.

https://github.com/jakartaee/jaxb-api/blob/master/api/src/main/java/jakarta/xml/bind/DatatypeConverterImpl.java

Regards,
Antonio.
