### ISSUE TITLE
systemId resolution regression introduced in 2.3.4+

### ISSUE THREAD

**Issue by mattrpav** [eclipse-ee4j/jaxb-ri#1732]
While modernizing the jaxb-tools (formerly the Highsource jaxb2-basics, maven-jaxb2-plugin, etc), we came across a use case that results in the need for us to work around systemId detection and handling.

We are looking for a better long-term solution for being able to wire into the xjc lifecycle, or send a config option to change the new default behavior.

@laurentschoelens has coded up a work-around and a demo project highlighting the issue. 

This is the identified change in jaxb-ri:
https://github.com/eclipse-ee4j/jaxb-ri/commit/b3a2c63e69b5fe079f3b5664d51ecf0992ad30c4

jaxb-tools PR with work-around: https://github.com/highsource/jaxb-tools/pull/329
JAXB Tools project: https://github.com/highsource/jaxb-tools

**Comment by lukasj** [comment]
likely introduced by the fix for #1502
