### ISSUE TITLE
Unexpected form=qualified Attribute in XSD Elements After Upgrading to JAXB-RI 4.0.3

### ISSUE THREAD

**Issue by danshome** [eclipse-ee4j/jaxb-ri#1742]
After we upgraded from JAXB-RI 4.0.2 to 4.03, we started getting form=qualified added to all our xsd elements generated using the com.sun.xml.ws:jaxws-maven-plugin. I don't find anything in the JAXB-RI release notes explaining the new behavior.

I tried adding the following to package-info.java, to revert to the old behavior. It didn't work whether I included the namespace or not.

@jakarta.xml.bind.annotation.XmlSchema (
elementFormDefault= XmlNsForm.UNQUALIFIED
)

For example, using JAXB-RI 4.0.3 "element1" was generated with form="qualified"...

<xs:element name="element1" type="xs:string" form="qualified" nillable="true" minOccurs="0" maxOccurs="unbounded"/>

If I move back to JAXB-RI 4.0.2, then form="qualified" is gone.

<xs:element name="element1" type="xs:string" nillable="true" minOccurs="0" maxOccurs="unbounded"/>

Is this expected behavior moving forward, or is this a bug?  If it is expected, could you please provide me with information about the expected behavior? It would be helpful if you could direct me to the release notes related to this change or any reference that I can use for my own release notes. This would mean all our clients will need to update their code, and it would be great to have something specific to share with them regarding the change in behavior. 

Thanks!

**Comment by cachescrubber** [comment]
The next issue reporting a braking change between 4.0.2 and 4.0.3.

See #1731, #1724
