### ISSUE TITLE
License information is inconsistent

### ISSUE THREAD

**Issue by skv-anders** [eclipse-ee4j/jaxb-ri#1749]
According to the README.md file, this project is licensed under EDL-1.0. According to the information in the artifacts produced, they are licensed under EDL-1.0. But according to LICENSE.md and the "about" section in Github it is licensed under BSD-3-Clause license.

I suggest that LICENSE.md should be updated

**Comment by lukasj** [comment]
EDL 1.0 is a BSD-3-Clause license, see ie https://lists.spdx.org/g/Spdx-legal/topic/request_for_adding_eclipse/67981884 for details
