### ISSUE TITLE
Add license information to pom xml

### ISSUE THREAD

**Issue by AlexanderBartash** [eclipse-ee4j/jaxb-ri#1817]
Please add license info into pom.xml it will fix https://github.com/jk1/Gradle-License-Report/issues/322

**Comment by lukasj** [comment]
to which pom? I can see it [here](https://github.com/eclipse-ee4j/jaxb-ri/blob/master/jaxb-ri/pom.xml#L42-L48)

**Comment by AlexanderBartash** [comment]
Sorry, my bad, did not notice that one.
