### ISSUE TITLE
Jaxb RI sources differ each time we build jaxb workspace

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#597]
I am filing this under docs though it for the jaxb source zip obtained by
building jaxb RI.
When we build jaxb RI, some classes for runtime are generated at build time.
Each time we build the order of the getters/setters and case logic differs.

When I talked to Kohsuke, he mentioned this can be fixed and this has to be done
somwhere in relaxng code. This is a problem who depends on sources to see that
sources differ each time RI is built.

For ex:
— a/src/com/sun/tools/jxc/gen/config/Classes.java Mon Feb 02 11:53:20 2009 -0800
+++ b/src/com/sun/tools/jxc/gen/config/Classes.java Tue Feb 03 11:07:48 2009 -0800
@@ -51,6 +51,18 @@ public class Classes extends NGCCHandler
$localName = $__local;
$qname = $__qname;
switch($_ngcc_current_state) {
+ case 2:
+ {
+ if(($__uri == "" && $__local == "excludes"))

{ + $runtime.onEnterElementConsumed($__uri, $__local, $__qname, $attrs); + $_ngcc_current_state = 6; + }
+ else { + $_ngcc_current_state = 1; + $runtime.sendEnterElement(super._cookie, $__uri, $__local, $__qname, $attrs); + }
+ }
+ break;
case 0:
{ revertToParentFromEnterElement(this, super._cookie, $__uri, $__local, $__qname, $attrs); @@ -84,18 +96,6 @@ public class Classes extends NGCCHandler }
}
break;
- case 2:
- {
- if(($__uri == "" && $__local == "excludes")) { - $runtime.onEnterElementConsumed($__uri, $__local, $__qname, $attrs); - $_ngcc_current_state = 6; - }
- else { - $_ngcc_current_state = 1; - $runtime.sendEnterElement(super._cookie, $__uri, $__local, $__qname, $attrs); - }
- }
- break;
default:
{
unexpectedEnterElement($__qname);
@@ -109,6 +109,12 @@ public class Classes extends NGCCHandler
$localName = $__local;
$qname = $__qname;
switch($_ngcc_current_state) {
+ case 2:
+ { + $_ngcc_current_state = 1; + $runtime.sendLeaveElement(super._cookie, $__uri, $__local, $__qname); + }
+ break;
case 0:
{
revertToParentFromLeaveElement(this, super._cookie, $__uri,
$__local, $__qname);
@@ -118,6 +124,17 @@ public class Classes extends NGCCHandler
{ $_ngcc_current_state = 3; $runtime.sendLeaveElement(super._cookie, $__uri, $__local, $__qname); + }
+ break;
+ case 1:
+ {
+ if(($__uri == "" && $__local == "classes")) { + $runtime.onLeaveElementConsumed($__uri, $__local, $__qname); + $_ngcc_current_state = 0; + }
+ else { + unexpectedLeaveElement($__qname); + }
}
break;
case 3:
@@ -131,28 +148,11 @@ public class Classes extends NGCCHandler
}
}
break;
- case 2:
- { - $_ngcc_current_state = 1; - $runtime.sendLeaveElement(super._cookie, $__uri, $__local, $__qname); - }
- break;
case 8:
{
if(($__uri == "" && $__local == "includes")) { $runtime.onLeaveElementConsumed($__uri, $__local, $__qname); $_ngcc_current_state = 2; - }
- else { - unexpectedLeaveElement($__qname); - }
- }
- break;
- case 1:
- {
- if(($__uri == "" && $__local == "classes")) { - $runtime.onLeaveElementConsumed($__uri, $__local, $__qname); - $_ngcc_current_state = 0; }
else {
unexpectedLeaveElement($__qname);
@@ -172,6 +172,12 @@ public class Classes extends NGCCHandler
$localName = $__local;
$qname = $__qname;
switch($_ngcc_current_state) {
+ case 2:
+ { + $_ngcc_current_state = 1; + $runtime.sendEnterAttribute(super._cookie, $__uri, $__local, $__qname); + }
+ break;
case 0:
{
revertToParentFromEnterAttribute(this, super._cookie, $__uri,
$__local, $__qname);
@@ -180,12 +186,6 @@ public class Classes extends NGCCHandler
case 4:
{ $_ngcc_current_state = 3; - $runtime.sendEnterAttribute(super._cookie, $__uri, $__local, $__qname); - }
- break;
- case 2:
- { - $_ngcc_current_state = 1; $runtime.sendEnterAttribute(super._cookie, $__uri, $__local, $__qname); }
break;
@@ -202,6 +202,12 @@ public class Classes extends NGCCHandler
$localName = $__local;
$qname = $__qname;
switch($_ngcc_current_state) {
+ case 2:
+ { + $_ngcc_current_state = 1; + $runtime.sendLeaveAttribute(super._cookie, $__uri, $__local, $__qname); + }
+ break;
case 0:
{
revertToParentFromLeaveAttribute(this, super._cookie, $__uri,
$__local, $__qname);
@@ -210,12 +216,6 @@ public class Classes extends NGCCHandler
case 4:
{ $_ngcc_current_state = 3; - $runtime.sendLeaveAttribute(super._cookie, $__uri, $__local, $__qname); - }
- break;
- case 2:
- { - $_ngcc_current_state = 1; $runtime.sendLeaveAttribute(super._cookie, $__uri, $__local, $__qname); }
break;
@@ -229,16 +229,22 @@ public class Classes extends NGCCHandler

public void text(String $value) throws SAXException {
switch($_ngcc_current_state) {
- case 0:
- { - revertToParentFromText(this, super._cookie, $value); - }
- break;
case 9:
{ include_content = $value; $_ngcc_current_state = 8; action2(); + }
+ break;
+ case 2:
+ { + $_ngcc_current_state = 1; + $runtime.sendText(super._cookie, $value); + }
+ break;
+ case 0:
+ { + revertToParentFromText(this, super._cookie, $value); }
break;
case 4:
@@ -248,6 +254,20 @@ public class Classes extends NGCCHandler
action0();
}
break;
+ case 10:
+ { + __text = $value; + $_ngcc_current_state = 9; + action3(); + }
+ break;
+ case 6:
+ { + __text = $value; + $_ngcc_current_state = 4; + action1(); + }
+ break;
case 3:
{ exclude_content = $value; @@ -255,31 +275,11 @@ public class Classes extends NGCCHandler action0(); }
break;
- case 2:
- { - $_ngcc_current_state = 1; - $runtime.sendText(super._cookie, $value); - }
- break;
- case 10:
- { - __text = $value; - $_ngcc_current_state = 9; - action3(); - }
- break;
case 8:
{ include_content = $value; $_ngcc_current_state = 8; action2(); - }
- break;
- case 6:
- { - __text = $value; - $_ngcc_current_state = 4; - action1(); }
break;
}

— a/src/com/sun/tools/jxc/gen/config/Config.java Mon Feb 02 11:53:20 2009 -0800
+++ b/src/com/sun/tools/jxc/gen/config/Config.java Tue Feb 03 11:07:48 2009 -0800
@@ -49,7 +49,46 @@ public class Config extends NGCCHandler
case 4:
{
if(($__uri == "" && $__local == "classes")) { - NGCCHandler h = new Classes(this, super._source, $runtime, 34); + NGCCHandler h = new Classes(this, super._source, $runtime, 22); + spawnChildFromEnterElement(h, $__uri, $__local, $__qname, $attrs); + }
+ else { + unexpectedEnterElement($__qname); + }
+ }
+ break;
+ case 7:
+ {
+ if(($ai = $runtime.getAttributeIndex("","baseDir"))>=0) { + $runtime.consumeAttribute($ai); + $runtime.sendEnterElement(super._cookie, $__uri, $__local, $__qname, $attrs); + }
+ else {+ unexpectedEnterElement($__qname);+ }
+ }
+ break;
+ case 2:
+ {
+ if(($__uri == "" && $__local == "schema")) { + NGCCHandler h = new Schema(this, super._source, $runtime, 20, baseDir); + spawnChildFromEnterElement(h, $__uri, $__local, $__qname, $attrs); + }
+ else {+ $_ngcc_current_state = 1;+ $runtime.sendEnterElement(super._cookie, $__uri, $__local,$__qname, $attrs);+ }
+ }
+ break;
+ case 0:
+ { + revertToParentFromEnterElement(this, super._cookie, $__uri, $__local, $__qname, $attrs); + }
+ break;
+ case 1:
+ {
+ if(($__uri == "" && $__local == "schema")) { + NGCCHandler h = new Schema(this, super._source, $runtime, 19, baseDir); spawnChildFromEnterElement(h, $__uri, $__local, $__qname, $attrs); }
else {
@@ -62,45 +101,6 @@ public class Config extends NGCCHandler
if(($__uri == "" && $__local == "config")) { $runtime.onEnterElementConsumed($__uri, $__local, $__qname, $attrs); $_ngcc_current_state = 7; - }
- else { - unexpectedEnterElement($__qname); - }
- }
- break;
- case 1:
- {
- if(($__uri == "" && $__local == "schema")) { - NGCCHandler h = new Schema(this, super._source, $runtime, 31, baseDir); - spawnChildFromEnterElement(h, $__uri, $__local, $__qname, $attrs); - }
- else {- unexpectedEnterElement($__qname);- }
- }
- break;
- case 0:
- { - revertToParentFromEnterElement(this, super._cookie, $__uri, $__local, $__qname, $attrs); - }
- break;
- case 2:
- {
- if(($__uri == "" && $__local == "schema")) { - NGCCHandler h = new Schema(this, super._source, $runtime, 32, baseDir); - spawnChildFromEnterElement(h, $__uri, $__local, $__qname, $attrs); - }
- else { - $_ngcc_current_state = 1; - $runtime.sendEnterElement(super._cookie, $__uri, $__local, $__qname, $attrs); - }
- }
- break;
- case 7:
- {
- if(($ai = $runtime.getAttributeIndex("","baseDir"))>=0) { - $runtime.consumeAttribute($ai); - $runtime.sendEnterElement(super._cookie, $__uri, $__local, $__qname, $attrs); }
else {
unexpectedEnterElement($__qname);
@@ -121,20 +121,15 @@ public class Config extends NGCCHandler
$localName = $__local;
$qname = $__qname;
switch($_ngcc_current_state) {
- case 1:
+ case 7:
{
- if(($__uri == "" && $__local == "config")) {
- $runtime.onLeaveElementConsumed($__uri, $__local, $__qname);
- $_ngcc_current_state = 0;
+ if(($ai = $runtime.getAttributeIndex("","baseDir"))>=0) { + $runtime.consumeAttribute($ai); + $runtime.sendLeaveElement(super._cookie, $__uri, $__local, $__qname); }
else { unexpectedLeaveElement($__qname); }
- }
- break;
- case 0:
- { - revertToParentFromLeaveElement(this, super._cookie, $__uri, $__local, $__qname); }
break;
case 2:
@@ -143,11 +138,16 @@ public class Config extends NGCCHandler
$runtime.sendLeaveElement(super._cookie, $__uri, $__local,
$__qname);
}
break;
- case 7:
+ case 0:
{
- if(($ai = $runtime.getAttributeIndex("","baseDir"))>=0) { - $runtime.consumeAttribute($ai); - $runtime.sendLeaveElement(super._cookie, $__uri, $__local, $__qname); + revertToParentFromLeaveElement(this, super._cookie, $__uri, $__local, $__qname); + }
+ break;
+ case 1:
+ {
+ if(($__uri == "" && $__local == "config")) { + $runtime.onLeaveElementConsumed($__uri, $__local, $__qname); + $_ngcc_current_state = 0; }
else {
unexpectedLeaveElement($__qname);
@@ -167,9 +167,14 @@ public class Config extends NGCCHandler
$localName = $__local;
$qname = $__qname;
switch($_ngcc_current_state) {
- case 0:
+ case 7:
{
- revertToParentFromEnterAttribute(this, super._cookie, $__uri,
$__local, $__qname);
+ if(($__uri == "" && $__local == "baseDir")) { + $_ngcc_current_state = 6; + }
+ else { + unexpectedEnterAttribute($__qname); + }
}
break;
case 2:
@@ -178,14 +183,9 @@ public class Config extends NGCCHandler
$runtime.sendEnterAttribute(super._cookie, $__uri, $__local,
$__qname);
}
break;
- case 7:
+ case 0:
{
- if(($__uri == "" && $__local == "baseDir")) { - $_ngcc_current_state = 6; - }
- else { - unexpectedEnterAttribute($__qname); - }
+ revertToParentFromEnterAttribute(this, super._cookie, $__uri,
$__local, $__qname);
}
break;
default:
@@ -201,9 +201,14 @@ public class Config extends NGCCHandler
$localName = $__local;
$qname = $__qname;
switch($_ngcc_current_state) {
- case 0:
+ case 5:
{
- revertToParentFromLeaveAttribute(this, super._cookie, $__uri,
$__local, $__qname);
+ if(($__uri == "" && $__local == "baseDir")) { + $_ngcc_current_state = 4; + }
+ else { + unexpectedLeaveAttribute($__qname); + }
}
break;
case 2:
@@ -212,14 +217,9 @@ public class Config extends NGCCHandler
$runtime.sendLeaveAttribute(super._cookie, $__uri, $__local,
$__qname);
}
break;
- case 5:
+ case 0:
{
- if(($__uri == "" && $__local == "baseDir")) { - $_ngcc_current_state = 4; - }
- else { - unexpectedLeaveAttribute($__qname); - }
+ revertToParentFromLeaveAttribute(this, super._cookie, $__uri,
$__local, $__qname);
}
break;
default:
@@ -233,17 +233,6 @@ public class Config extends NGCCHandler
public void text(String $value) throws SAXException {
int $ai;
switch($_ngcc_current_state) {
- case 0:
- { - revertToParentFromText(this, super._cookie, $value); - }
- break;
- case 2:
- { - $_ngcc_current_state = 1; - $runtime.sendText(super._cookie, $value); - }
- break;
case 7:
{
if(($ai = $runtime.getAttributeIndex("","baseDir"))>=0) { @@ -259,25 +248,36 @@ public class Config extends NGCCHandler action1(); }
break;
+ case 2:
+ { + $_ngcc_current_state = 1; + $runtime.sendText(super._cookie, $value); + }
+ break;
+ case 0:
+ { + revertToParentFromText(this, super._cookie, $value); + }
+ break;
}
}

public void onChildCompleted(Object $__result__, int $__cookie__, boolean
$__needAttCheck__)throws SAXException {
switch($__cookie__) {
- case 34:
+ case 22:
{ classes = ((Classes)$__result__); $_ngcc_current_state = 2; }
break;
- case 31:
+ case 20:
{ _schema = ((Schema)$__result__); action0(); $_ngcc_current_state = 1; }
break;
- case 32:
+ case 19:
{
_schema = ((Schema)$__result__);
action0();

— a/src/com/sun/tools/jxc/gen/config/Schema.java Mon Feb 02 11:53:20 2009 -0800
+++ b/src/com/sun/tools/jxc/gen/config/Schema.java Tue Feb 03 11:07:48 2009 -0800
@@ -41,6 +41,17 @@ public class Schema extends NGCCHandler
$localName = $__local;
$qname = $__qname;
switch($_ngcc_current_state) {
+ case 10:
+ {
+ if(($__uri == "" && $__local == "schema")) {+ $runtime.onEnterElementConsumed($__uri, $__local, $__qname,$attrs);+ $_ngcc_current_state = 6;+ }

+ else

{ + unexpectedEnterElement($__qname); + }

+ }
+ break;
case 0:
{
revertToParentFromEnterElement(this, super._cookie, $__uri,
$__local, $__qname, $attrs);
@@ -67,17 +78,6 @@ public class Schema extends NGCCHandler
else

{ $_ngcc_current_state = 2; $runtime.sendEnterElement(super._cookie, $__uri, $__local, $__qname, $attrs); - }

*   }
*   break;
*   case 10:
*   {
*   if(($__uri == "" && $__local == "schema")) { - $runtime.onEnterElementConsumed($__uri, $__local, $__qname, $attrs); - $_ngcc_current_state = 6; - }
*   else { - unexpectedEnterElement($__qname); }

    }
    break;
    @@ -112,17 +112,6 @@ public class Schema extends NGCCHandler
    }
    }
    break;

*   case 1:
*   {
*   if(($__uri == "" && $__local == "schema")) { - $runtime.onLeaveElementConsumed($__uri, $__local, $__qname); - $_ngcc_current_state = 0; - }
*   else { - unexpectedLeaveElement($__qname); - }
*   }
*   break;
    case 6:
    {
    if(($ai = $runtime.getAttributeIndex("","namespace"))>=0)Unknown macro: {@@ -132,6 +121,17 @@ public class Schema extends NGCCHandler else { $_ngcc_current_state = 2; $runtime.sendLeaveElement(super._cookie, $__uri, $__local, $__qname); + }+ }

    + break;
    + case 1:
    +

    Unknown macro: {+ if(($__uri == "" && $__local == "schema")) { + $runtime.onLeaveElementConsumed($__uri, $__local, $__qname); + $_ngcc_current_state = 0; + }+ else { + unexpectedLeaveElement($__qname); } }

    break;
    @@ -193,20 +193,20 @@ public class Schema extends NGCCHandler
    revertToParentFromLeaveAttribute(this, super._cookie, $__uri,
    $__local, $__qname);
    }
    break;
    + case 3:
    +

    Unknown macro: {+ if(($__uri == "" && $__local == "location")) { + $_ngcc_current_state = 1; + }+ else { + unexpectedLeaveAttribute($__qname); + }+ }

    + break;
    case 2:

    { $_ngcc_current_state = 1; $runtime.sendLeaveAttribute(super._cookie, $__uri, $__local, $__qname); - }
*   break;
*   case 7:
*   {
*   if(($__uri == "" && $__local == "namespace")) { - $_ngcc_current_state = 2; - }
*   else { - unexpectedLeaveAttribute($__qname); - }

    }
    break;
    case 6:
    @@ -215,10 +215,10 @@ public class Schema extends NGCCHandler
    $runtime.sendLeaveAttribute(super._cookie, $__uri, $__local,
    $__qname);
    }
    break;

*   case 3:
    + case 7:
    {
*   if(($__uri == "" && $__local == "location")) {
*   $_ngcc_current_state = 1;
    + if(($__uri == "" && $__local == "namespace")) { + $_ngcc_current_state = 2; }

    else

    { unexpectedLeaveAttribute($__qname); @@ -241,6 +241,13 @@ public class Schema extends NGCCHandler revertToParentFromText(this, super._cookie, $value); }

    break;
    + case 4:
    +

    { + loc = $value; + $_ngcc_current_state = 3; + action0(); + }

    + break;
    case 2:

    Unknown macro: { if(($ai = $runtime.getAttributeIndex("","location"))>=0) { @@ -253,19 +260,6 @@ public class Schema extends NGCCHandler } }

    break;

*   case 8:
*   { - namespace = $value; - $_ngcc_current_state = 7; - }
*   break;
*   case 4:
*   { - loc = $value; - $_ngcc_current_state = 3; - action0(); - }
*   break;
    case 6:Unknown macro: { if(($ai = $runtime.getAttributeIndex("","namespace"))>=0) { @@ -276,6 +270,12 @@ public class Schema extends NGCCHandler $_ngcc_current_state = 2; $runtime.sendText(super._cookie, $value); }+ }

    + break;
    + case 8:
    +

    { + namespace = $value; + $_ngcc_current_state = 7; }

    break;
    }

— a/src/com/sun/xml/bind/v2/schemagen/xmlschema/Occurs.java Mon Feb 02
11:53:20 2009 -0800
+++ b/src/com/sun/xml/bind/v2/schemagen/xmlschema/Occurs.java Tue Feb 03
11:07:48 2009 -0800
@@ -13,9 +13,9 @@ public interface Occurs
public Occurs minOccurs(int value);

@XmlAttribute
+ public Occurs maxOccurs(String value);
+
+ @XmlAttribute
public Occurs maxOccurs(int value);

*   @XmlAttribute
*   public Occurs maxOccurs(String value);
    -
    }

— a/src/com/sun/xml/bind/v2/schemagen/xmlschema/SimpleType.java Mon Feb 02
11:53:20 2009 -0800
+++ b/src/com/sun/xml/bind/v2/schemagen/xmlschema/SimpleType.java Tue Feb 03
11:07:48 2009 -0800
@@ -12,10 +12,10 @@ public interface SimpleType

@XmlAttribute("final")

*   public SimpleType _final(String[] value);
    + public SimpleType _final(String value);

@XmlAttribute("final")

*   public SimpleType _final(String value);
    + public SimpleType _final(String[] value);

@XmlAttribute
public SimpleType name(String value);
#### Environment
Operating System: All
Platform: Macintosh
#### Affected Versions
[2.1.9]

**Comment by lukasj** [comment]
no longer being generated during the build
