### ISSUE TITLE
sub classes are generated in different parent classes with jdk6 update 14

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#650]
Previously using xjc to generate java classes for asap.xsd an observers class
would be generated as a sub class in the SetPropertiesRs class. After updating
to jdk6 the Observers class is now being added to the GetPropertiesRs class. The
issue is ultimately traced to the jdk hashMap class hash function being changed
so that the hashMaps are in a different order that before. The jaxb SchemaImpl
class uses hashMaps to store the elements in the schema, which later is used to
generate the element classes. Before jdk6 for the asap.xsd the hashmap looked
like - {ResultData=ResultData element declaration, SubscribeRq=SubscribeRq
element declaration, CompletedRs=CompletedRs element declaration,
Instance=Instance element declaration, SetPropertiesRs=SetPropertiesRs element
declaration, UnsubscribeRs=UnsubscribeRs element declaration,
UnsubscribeRq=UnsubscribeRq element declaration, StateChangedRq=StateChangedRq
element declaration, GetPropertiesRq=GetPropertiesRq element declaration,
ListInstancesRs=ListInstancesRs element declaration, ContextData=ContextData
element declaration, CreateInstanceRs=CreateInstanceRs element declaration,
CompletedRq=CompletedRq element declaration, SetPropertiesRq=SetPropertiesRq
element declaration, GetPropertiesRs=GetPropertiesRs element declaration,
ChangeStateRs=ChangeStateRs element declaration, SubscribeRs=SubscribeRs element
declaration, ChangeStateRq=ChangeStateRq element declaration, Event=Event
element declaration, CreateInstanceRq=CreateInstanceRq element declaration,
ListInstancesRq=ListInstancesRq element declaration,
StateChangedRs=StateChangedRs element declaration

Now with jdk 6 it is -

ContextData=ContextData element declaration, ResultData=ResultData element
declaration, Instance=Instance element declaration,
GetPropertiesRs=GetPropertiesRs element declaration,
GetPropertiesRq=GetPropertiesRq element declaration, Event=Event element
declaration, ListInstancesRq=ListInstancesRq element declaration,
UnsubscribeRq=UnsubscribeRq element declaration, SetPropertiesRs=SetPropertiesRs
element declaration, UnsubscribeRs=UnsubscribeRs element declaration,
SetPropertiesRq=SetPropertiesRq element declaration,
StateChangedRs=StateChangedRs element declaration,
ListInstancesRs=ListInstancesRs element declaration,
CreateInstanceRs=CreateInstanceRs element declaration,
ChangeStateRq=ChangeStateRq element declaration, StateChangedRq=StateChangedRq
element declaration, CreateInstanceRq=CreateInstanceRq element declaration,
ChangeStateRs=ChangeStateRs element declaration, CompletedRq=CompletedRq element
declaration, SubscribeRs=SubscribeRs element declaration,
SubscribeRq=SubscribeRq element declaration, CompletedRs=CompletedRs element
declaration

Being that the GetPropertiesRs class is listed first in the hashmap now the
Observers class is generated there and all references to it in other classes are
GetPropertiesRs.Observers rather than SetPropertiesRs.Observers in the previous jdk.

We've currently changed our code to handle the class location being different
but are concerned that this may cause issues elsewhere that we have not seen.
#### Environment
Operating System: Windows XP
Platform: PC
#### Affected Versions
[2.1.10]

**Comment by lukasj** [comment]
LinkedHashMap is there
