### ISSUE TITLE
Support java.util.Map and it's subtypes, as it's in the spec

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#791]
Section 8.5.4 of the JAXB spec states that java.util.Map (and its subtypes) must
be supported. The RI does not, does it?

I didn't find any issues with "Map" in the Summary.

I'm not shure about the exact version... the one shipped with OpenJDK-6.
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[2.1]

**Comment by pavel** [comment]
@Tomas-Kraus Thanks for notifying me, but it does not seem that I'm involved in this project in any way.

https://blog.github.com/2011-03-23-mention-somebody-they-re-notified/

**Comment by lukasj** [comment]
moved the spec part to https://github.com/eclipse-ee4j/jaxb-api/issues/237
