### ISSUE TITLE
JAnnotationArrayMember.annotations() is causing ClassCastException

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#884]
<tt>JAnnotationArrayMember</tt> adds to <tt>values</tt> field annotations, which are not of type <tt>JAnnotationUse</tt>. Hence model causes <tt>ClassCastException</tt> when attempt is made to iterate this collection via <tt>JAnnotationArrayMember.annotations()</tt>:

```
// ann represents @XmlType class-level annotation. // ClassCastException here: for (JAnnotationUse ann : ((JAnnotationArrayMember) annotation.getAnnotationMembers().get("propOrder")).annotations()) {
	...
}
```
#### Affected Versions
[2.2.5]

**Comment by lukasj** [comment]
this has been already fixed
