### ISSUE TITLE
Disable annotation processing warning in JDK8

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#945]
Fix this code according to JDK8:

@Override
public SourceVersion getSupportedSourceVersion() {
if (SourceVersion.latest().compareTo(SourceVersion.RELEASE_6) > 0)

{ return SourceVersion.valueOf("RELEASE_7"); }

else

{ return SourceVersion.RELEASE_6; }

}
#### Affected Versions
[2.2.7]

**Comment by lukasj** [comment]
fixed already
